/* Generated by res-to-ts. DO NOT EDIT */
/* eslint-disable */
/* istanbul ignore file */

import { Buffer } from 'node:buffer';
import { cpSync, existsSync, mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, sep } from 'node:path';

/**
 * Get the path to the resource data/electionTwoPartyPrimary/csvFiles/batchResults.csv.
 */
function getResourcePath(): string {
  let rootDir = __dirname;
  do {
    if (existsSync(join(rootDir, 'package.json'))) {
      return join(
        rootDir,
        'data/electionTwoPartyPrimary/csvFiles/batchResults.csv'
      );
    }
    let parentDir = dirname(rootDir);
    if (parentDir === '.' || parentDir === rootDir) {
      break;
    }
    rootDir = parentDir;
  } while (true);
  throw new Error('Could not find resource path');
}

/**
 * MIME type of data/electionTwoPartyPrimary/csvFiles/batchResults.csv.
 */
export const mimeType = 'text/csv';

/**
 * Path to a file containing this file's contents.
 */
export function asFilePath(): string {
  const directoryPath = mkdtempSync(tmpdir() + sep);
  const filePath = join(directoryPath, 'batchResults.csv');
  cpSync(getResourcePath(), filePath);
  return filePath;
}

/**
 * Convert to a `data:` URL of data/electionTwoPartyPrimary/csvFiles/batchResults.csv, suitable for embedding in HTML.
 */
export function asDataUrl(): string {
  return `data:${mimeType};base64,${asBuffer().toString('base64')}`;
}

/**
 * Raw data of data/electionTwoPartyPrimary/csvFiles/batchResults.csv.
 */
export function asBuffer(): Buffer {
  return readFileSync(getResourcePath());
}

/**
 * Text content of data/electionTwoPartyPrimary/csvFiles/batchResults.csv.
 */
export function asText(): string {
  return readFileSync(getResourcePath(), 'utf-8');
}
