import { UiStringsPackage } from '@votingworks/types';

// ui-strings.json is currently generated by running VxDesign and logging the UI
// strings package generated. For example, you can load a ballot preview and add
// a log line to the function `getBallotPreviewPdf` in `app.ts`:
// console.log(JSON.stringify(translatedStrings));
// TODO We should automate this process
import * as uiStringsJson from './ui-strings.json';

export const uiStrings: UiStringsPackage = JSON.parse(uiStringsJson.asText());

export * from './election.json';
