/** Stub for 'crypto' module, generated by script/build-stubs. DO NOT EDIT */
/* eslint-disable */
/* istanbul ignore file */

function __stubFnDoNotCall(): never {
  throw new Error('this function is a stub and should never be called');
}
/** Stub for argon2 */
export const argon2 = __stubFnDoNotCall;
/** Stub for argon2Sync */
export const argon2Sync = __stubFnDoNotCall;
/** Stub for checkPrime */
export const checkPrime = __stubFnDoNotCall;
/** Stub for checkPrimeSync */
export const checkPrimeSync = __stubFnDoNotCall;
/** Stub for createCipheriv */
export const createCipheriv = __stubFnDoNotCall;
/** Stub for createDecipheriv */
export const createDecipheriv = __stubFnDoNotCall;
/** Stub for createDiffieHellman */
export const createDiffieHellman = __stubFnDoNotCall;
/** Stub for createDiffieHellmanGroup */
export const createDiffieHellmanGroup = __stubFnDoNotCall;
/** Stub for createECDH */
export const createECDH = __stubFnDoNotCall;
/** Stub for createHash */
export const createHash = __stubFnDoNotCall;
/** Stub for createHmac */
export const createHmac = __stubFnDoNotCall;
/** Stub for createPrivateKey */
export const createPrivateKey = __stubFnDoNotCall;
/** Stub for createPublicKey */
export const createPublicKey = __stubFnDoNotCall;
/** Stub for createSecretKey */
export const createSecretKey = __stubFnDoNotCall;
/** Stub for createSign */
export const createSign = __stubFnDoNotCall;
/** Stub for createVerify */
export const createVerify = __stubFnDoNotCall;
/** Stub for diffieHellman */
export const diffieHellman = __stubFnDoNotCall;
/** Stub for generatePrime */
export const generatePrime = __stubFnDoNotCall;
/** Stub for generatePrimeSync */
export const generatePrimeSync = __stubFnDoNotCall;
/** Stub for getCiphers */
export const getCiphers = __stubFnDoNotCall;
/** Stub for getCipherInfo */
export const getCipherInfo = __stubFnDoNotCall;
/** Stub for getCurves */
export const getCurves = __stubFnDoNotCall;
/** Stub for getDiffieHellman */
export const getDiffieHellman = __stubFnDoNotCall;
/** Stub for getHashes */
export const getHashes = __stubFnDoNotCall;
/** Stub for hkdf */
export const hkdf = __stubFnDoNotCall;
/** Stub for hkdfSync */
export const hkdfSync = __stubFnDoNotCall;
/** Stub for pbkdf2 */
export const pbkdf2 = __stubFnDoNotCall;
/** Stub for pbkdf2Sync */
export const pbkdf2Sync = __stubFnDoNotCall;
/** Stub for generateKeyPair */
export const generateKeyPair = __stubFnDoNotCall;
/** Stub for generateKeyPairSync */
export const generateKeyPairSync = __stubFnDoNotCall;
/** Stub for generateKey */
export const generateKey = __stubFnDoNotCall;
/** Stub for generateKeySync */
export const generateKeySync = __stubFnDoNotCall;
/** Stub for privateDecrypt */
export const privateDecrypt = __stubFnDoNotCall;
/** Stub for privateEncrypt */
export const privateEncrypt = __stubFnDoNotCall;
/** Stub for publicDecrypt */
export const publicDecrypt = __stubFnDoNotCall;
/** Stub for publicEncrypt */
export const publicEncrypt = __stubFnDoNotCall;
/** Stub for randomBytes */
export const randomBytes = __stubFnDoNotCall;
/** Stub for randomFill */
export const randomFill = __stubFnDoNotCall;
/** Stub for randomFillSync */
export const randomFillSync = __stubFnDoNotCall;
/** Stub for randomInt */
export const randomInt = __stubFnDoNotCall;
/** Stub for randomUUID */
export const randomUUID = __stubFnDoNotCall;
/** Stub for randomUUIDv7 */
export const randomUUIDv7 = __stubFnDoNotCall;
/** Stub for scrypt */
export const scrypt = __stubFnDoNotCall;
/** Stub for scryptSync */
export const scryptSync = __stubFnDoNotCall;
/** Stub for sign */
export const sign = __stubFnDoNotCall;
/** Stub for setEngine */
export const setEngine = __stubFnDoNotCall;
/** Stub for timingSafeEqual */
export const timingSafeEqual = __stubFnDoNotCall;
/** Stub for getFips */
export const getFips = __stubFnDoNotCall;
/** Stub for setFips */
export const setFips = __stubFnDoNotCall;
/** Stub for verify */
export const verify = __stubFnDoNotCall;
/** Stub for hash */
export const hash = __stubFnDoNotCall;
/** Stub for encapsulate */
export const encapsulate = __stubFnDoNotCall;
/** Stub for decapsulate */
export const decapsulate = __stubFnDoNotCall;
/** Stub for Certificate */
export const Certificate = __stubFnDoNotCall;
/** Stub for Cipheriv */
export const Cipheriv = __stubFnDoNotCall;
/** Stub for Decipheriv */
export const Decipheriv = __stubFnDoNotCall;
/** Stub for DiffieHellman */
export const DiffieHellman = __stubFnDoNotCall;
/** Stub for DiffieHellmanGroup */
export const DiffieHellmanGroup = __stubFnDoNotCall;
/** Stub for ECDH */
export const ECDH = __stubFnDoNotCall;
/** Stub for Hash */
export const Hash = __stubFnDoNotCall;
/** Stub for Hmac */
export const Hmac = __stubFnDoNotCall;
/** Stub for KeyObject */
export const KeyObject = __stubFnDoNotCall;
/** Stub for Sign */
export const Sign = __stubFnDoNotCall;
/** Stub for Verify */
export const Verify = __stubFnDoNotCall;
/** Stub for X509Certificate */
export const X509Certificate = __stubFnDoNotCall;
/** Stub for secureHeapUsed */
export const secureHeapUsed = __stubFnDoNotCall;
/** Stub for constants */
export const constants = {
  OPENSSL_VERSION_NUMBER: 810549360,
  SSL_OP_ALL: 2147485776,
  SSL_OP_ALLOW_NO_DHE_KEX: 1024,
  SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION: 262144,
  SSL_OP_CIPHER_SERVER_PREFERENCE: 4194304,
  SSL_OP_CISCO_ANYCONNECT: 32768,
  SSL_OP_COOKIE_EXCHANGE: 8192,
  SSL_OP_CRYPTOPRO_TLSEXT_BUG: 2147483648,
  SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS: 2048,
  SSL_OP_LEGACY_SERVER_CONNECT: 4,
  SSL_OP_NO_COMPRESSION: 131072,
  SSL_OP_NO_ENCRYPT_THEN_MAC: 524288,
  SSL_OP_NO_QUERY_MTU: 4096,
  SSL_OP_NO_RENEGOTIATION: 1073741824,
  SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION: 65536,
  SSL_OP_NO_SSLv2: 0,
  SSL_OP_NO_SSLv3: 33554432,
  SSL_OP_NO_TICKET: 16384,
  SSL_OP_NO_TLSv1: 67108864,
  SSL_OP_NO_TLSv1_1: 268435456,
  SSL_OP_NO_TLSv1_2: 134217728,
  SSL_OP_NO_TLSv1_3: 536870912,
  SSL_OP_PRIORITIZE_CHACHA: 2097152,
  SSL_OP_TLS_ROLLBACK_BUG: 8388608,
  ENGINE_METHOD_RSA: 1,
  ENGINE_METHOD_DSA: 2,
  ENGINE_METHOD_DH: 4,
  ENGINE_METHOD_RAND: 8,
  ENGINE_METHOD_EC: 2048,
  ENGINE_METHOD_CIPHERS: 64,
  ENGINE_METHOD_DIGESTS: 128,
  ENGINE_METHOD_PKEY_METHS: 512,
  ENGINE_METHOD_PKEY_ASN1_METHS: 1024,
  ENGINE_METHOD_ALL: 65535,
  ENGINE_METHOD_NONE: 0,
  DH_CHECK_P_NOT_SAFE_PRIME: 2,
  DH_CHECK_P_NOT_PRIME: 1,
  DH_UNABLE_TO_CHECK_GENERATOR: 4,
  DH_NOT_SUITABLE_GENERATOR: 8,
  RSA_PKCS1_PADDING: 1,
  RSA_NO_PADDING: 3,
  RSA_PKCS1_OAEP_PADDING: 4,
  RSA_X931_PADDING: 5,
  RSA_PKCS1_PSS_PADDING: 6,
  RSA_PSS_SALTLEN_DIGEST: -1,
  RSA_PSS_SALTLEN_MAX_SIGN: -2,
  RSA_PSS_SALTLEN_AUTO: -2,
  defaultCoreCipherList:
    'TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA',
  TLS1_VERSION: 769,
  TLS1_1_VERSION: 770,
  TLS1_2_VERSION: 771,
  TLS1_3_VERSION: 772,
  POINT_CONVERSION_COMPRESSED: 2,
  POINT_CONVERSION_UNCOMPRESSED: 4,
  POINT_CONVERSION_HYBRID: 6,
  defaultCipherList:
    'TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA',
};
/** Stub for webcrypto */
export const webcrypto = {};
/** Stub for subtle */
export const subtle = {};
/** Stub for getRandomValues */
export const getRandomValues = __stubFnDoNotCall;
