/* eslint-disable max-classes-per-file */
import { Buffer } from 'node:buffer';
import path from 'node:path';
import { Mocked, MockFunction, mockFunction } from '@votingworks/test-utils';

import { Card, CardStatus } from '../src/card';
import {
  CardReader,
  OnReaderStatusChange,
  ReaderStatus,
} from '../src/card_reader';
import { CardType } from '../src/certs';
import { JavaCard } from '../src/java_card';

/**
 * A mock card reader
 */
export class MockCardReader implements Pick<CardReader, 'transmit'> {
  private readonly onReaderStatusChange: OnReaderStatusChange;

  constructor(input: ConstructorParameters<typeof CardReader>[0]) {
    this.onReaderStatusChange = input.onReaderStatusChange;
  }

  setReaderStatus(readerStatus: ReaderStatus): void {
    this.onReaderStatusChange(readerStatus);
  }

  // eslint-disable-next-line vx/gts-no-public-class-fields
  disconnectCard: MockFunction<CardReader['disconnectCard']> =
    mockFunction('disconnectCard');

  // eslint-disable-next-line vx/gts-no-public-class-fields
  transmit: MockFunction<CardReader['transmit']> = mockFunction('transmit');
}

/**
 * Builds a mock card instance
 */
export function buildMockCard(): Mocked<Card> {
  return {
    getCardStatus: mockFunction('getCardStatus'),
    checkPin: mockFunction('checkPin'),
    program: mockFunction('program'),
    readData: mockFunction('readData'),
    writeData: mockFunction('writeData'),
    clearData: mockFunction('clearData'),
    unprogram: mockFunction('unprogram'),
    disconnect: mockFunction('disconnect'),
  };
}

/**
 * Asserts that all the expected calls to all the methods of a mock card were made
 */
export function mockCardAssertComplete(mockCard: Mocked<Card>): void {
  for (const mockMethod of Object.values(mockCard)) {
    mockMethod.assertComplete();
  }
}

/**
 * An extension of the Java Card class with a method for manually setting the card status to
 * simplify setup for Java Card tests that require the card to be in a specific starting state
 */
export class TestJavaCard extends JavaCard {
  setCardStatus(
    cardStatus: CardStatus,
    lastValidatedCardIdentityCert?: Buffer
  ): void {
    this.cardStatus = cardStatus;
    this.lastValidatedCardIdentityCert = lastValidatedCardIdentityCert;
  }
}

/**
 * An identifier for a set of test files
 */
export type TestFileSetId = '1' | '2';

interface CardAgnosticTestFile {
  fileType:
    | 'vx-admin-cert-authority-cert.der'
    | 'vx-admin-cert-authority-cert.pem'
    | 'vx-admin-private-key.pem'
    | 'vx-central-scan-cert.pem'
    | 'vx-central-scan-private-key.pem'
    | 'vx-cert-authority-cert.pem'
    | 'vx-mark-cert.pem'
    | 'vx-mark-private-key.pem'
    | 'vx-poll-book-cert-authority-cert.der'
    | 'vx-poll-book-cert-authority-cert.pem'
    | 'vx-poll-book-private-key.pem'
    | 'vx-private-key.pem'
    | 'vx-scan-cert.pem'
    | 'vx-scan-private-key.pem';
  setId?: TestFileSetId;
}

interface CardSpecificTestFile {
  fileType:
    | 'card-identity-cert-expired.der'
    | 'card-identity-cert.der'
    | 'card-identity-private-key.pem'
    | 'card-identity-public-key.der'
    | 'card-vx-cert.der'
    | 'card-vx-private-key.pem'
    | 'card-vx-public-key.der';
  setId?: TestFileSetId;
  cardType: CardType;
  programmingMachineType?: 'admin' | 'poll-book';
}

type TestFile = CardAgnosticTestFile | CardSpecificTestFile;

function isCardSpecificTestFile(
  testFile: TestFile
): testFile is CardSpecificTestFile {
  return 'cardType' in testFile;
}

/**
 * Gets the file path of a test key or cert generated by ./scripts/generate-test-keys-and-certs
 */
export function getTestFilePath(testFile: TestFile): string {
  const setId: TestFileSetId = testFile.setId ?? '1';
  const pathParts: string[] = [
    '.',
    'certs',
    'test',
    `set-${setId}`,
    isCardSpecificTestFile(testFile) && testFile.cardType,
    isCardSpecificTestFile(testFile) &&
      testFile.cardType !== 'vendor' &&
      `vx-${testFile.programmingMachineType ?? 'admin'}-programmed`,
    testFile.fileType,
  ].filter((part): part is string => Boolean(part));
  return path.join(...pathParts);
}
