packages:
  # include all the frontends and their prodservers
  - 'frontends/*'
  - 'frontends/*/prodserver'

  # include all the services
  - 'services/*'

  # include all the libraries and our custom types
  - 'libs/*'
  - 'libs/@types/*'

  # include all integration tests
  - 'integration-testing/*'

  # include top-level development project
  - 'codemods'
  - 'internal/*'
  - 'script'
