packages:
  # include all the apps, frontends (+ prodservers) and backends
  - 'apps/*/frontend'
  - 'apps/*/frontend/prodserver'
  - 'apps/*/backend'
  - 'apps/*/integration-testing'

  # include all the frontends and their prodservers
  - 'frontends/*'
  - 'frontends/*/prodserver'

  # include all the services
  - 'services/*'

  # include all the libraries and our custom types
  - 'libs/*'
  - 'libs/@types/*'
  - 'libs/grout/*'

  # include all integration tests
  - 'integration-testing/*'

  # include top-level development project
  - 'codemods'
  - 'script'
