packages:
  # include all the apps, frontends (+ prodservers) and backends
  - 'apps/*/frontend'
  - 'apps/*/frontend/prodserver'
  - 'apps/*/backend'
  - 'apps/*/integration-testing'
  - 'apps/*/playwright'

  # include all the libraries and our custom types
  - 'libs/*'
  - 'libs/@types/*'
  - 'libs/grout/*'
  - 'libs/dev-dock/*'

  # include top-level development project
  - 'codemods'
  - 'script'

  # code exercises
  - 'docs/exercises'
