import { defineConfig } from '../../vitest.config.shared.mjs';

export default defineConfig({
  test: {
    coverage: {
      // src/cdf/*/index.ts is generated by cdf-schema-builder — coverage of
      // its output is noise, not signal; cli.ts is a dev harness
      exclude: [
        'src/index.ts',
        'src/cdf/*/index.ts',
        'src/cdf/ballot-definition/cli.ts',
      ],
      // Remove after migration to coverage-check is complete
      thresholds: {
        lines: 0,
        branches: 0,
      },
    },
  },
});
