/* Generated by res-to-ts. DO NOT EDIT */
/* eslint-disable */
/* istanbul ignore file */
  
import { mkdtempSync, cpSync } from 'fs';
import { tmpdir } from 'os';
import { resolve, sep } from 'path';

export function asDirectoryPath(): string {
  const tmpDir = mkdtempSync(tmpdir() + sep);
  const resolved = resolve(
    __dirname,
    '../../../../data/electionMinimalExhaustiveSample/cdf-cvr-files/standard'
  );
  cpSync(resolved, tmpDir, { recursive: true });
  return tmpDir;
}

