import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export function generateFontAwesomeStyles(outputPath: string): void {
  const fontAwesomePath = require.resolve('@fortawesome/fontawesome-svg-core');
  const css = readFileSync(join(fontAwesomePath, '../styles.css'), 'utf8');

  writeFileSync(
    outputPath,
    `// The content of this file is auto-generated. Do not edit this file directly.

/**
 * In a browser environment, \`font-awesome\` handles loading its own styles.
 * But in a server environment, we need to add it ourselves.
 */
export const FONT_AWESOME_STYLES = \`${css}\`;
`
  );
}
