import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, expect, test } from 'vitest';
import { mockWritable } from '../test/mock_writable.js';
import { main } from './cli.js';

const USAGE = 'Usage: cdf-schema-builder <schema.xml> <schema.json>\n';

const EMPTY_XSD = `<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" targetNamespace="http://itl.nist.gov/ns/voting/1500-101/v1" version="1.0.2" xmlns="http://itl.nist.gov/ns/voting/1500-101/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
</xsd:schema>
`;

const EMPTY_JSON_SCHEMA = JSON.stringify({
  $schema: 'http://json-schema.org/draft-04/schema#',
  definitions: {},
});

const tempDirs: string[] = [];

function writeTempFiles(xsdName: string): {
  xsdPath: string;
  jsonPath: string;
} {
  const dir = mkdtempSync(join(tmpdir(), 'cdf-schema-builder-'));
  tempDirs.push(dir);
  const xsdPath = join(dir, xsdName);
  const jsonPath = join(dir, 'schema.json');
  writeFileSync(xsdPath, EMPTY_XSD);
  writeFileSync(jsonPath, EMPTY_JSON_SCHEMA);
  return { xsdPath, jsonPath };
}

function run(argv: string[]) {
  const stdout = mockWritable();
  const stderr = mockWritable();
  const exitCode = main(argv, { stdout, stderr });
  return { exitCode, stdout: stdout.toString(), stderr: stderr.toString() };
}

afterEach(() => {
  for (const dir of tempDirs.splice(0)) {
    rmSync(dir, { recursive: true, force: true });
  }
});

test.each(['-h', '--help'])('%s prints usage', (flag) => {
  expect(run([flag])).toEqual({ exitCode: 0, stdout: USAGE, stderr: '' });
});

test('no arguments', () => {
  expect(run([])).toEqual({
    exitCode: 1,
    stdout: '',
    stderr: `error: missing XSD or JSON schema file path\n${USAGE}`,
  });
});

test('unknown option', () => {
  const { xsdPath, jsonPath } = writeTempFiles('schema.xsd');
  expect(run(['--bogus', xsdPath, jsonPath])).toEqual({
    exitCode: 0,
    stdout: expect.stringContaining('DO NOT EDIT THIS FILE'),
    stderr: `error: unknown option: --bogus\n${USAGE}`,
  });
});

test('unknown file extension', () => {
  expect(run(['schema.txt'])).toEqual({
    exitCode: 1,
    stdout: '',
    stderr: `error: unknown file extension: schema.txt\n${USAGE}error: missing XSD or JSON schema file path\n${USAGE}`,
  });
});

test('missing JSON schema path', () => {
  expect(run(['schema.xsd'])).toEqual({
    exitCode: 1,
    stdout: '',
    stderr: `error: missing XSD or JSON schema file path\n${USAGE}`,
  });
});

test('missing XSD schema path', () => {
  expect(run(['schema.json'])).toEqual({
    exitCode: 1,
    stdout: '',
    stderr: `error: missing XSD or JSON schema file path\n${USAGE}`,
  });
});

test.each(['schema.xsd', 'schema.xml'])(
  'builds a schema from %s',
  (xsdName) => {
    const { xsdPath, jsonPath } = writeTempFiles(xsdName);
    expect(run([xsdPath, jsonPath])).toEqual({
      exitCode: 0,
      stdout: expect.stringContaining('DO NOT EDIT THIS FILE'),
      stderr: '',
    });
  }
);
