/* Generated by res-to-ts. DO NOT EDIT */
/* eslint-disable */
/* istanbul ignore file */

import * as fs from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve, sep } from 'node:path';

const copiedDirectories: string[] = [];

if (typeof jest !== 'undefined') {
  afterAll(() => {
    for (const copiedDirectory of copiedDirectories) {
      fs.rmSync(copiedDirectory, { recursive: true, force: true });
    }
  });
}

export function asDirectoryPath(): string {
  const tmpDir = fs.mkdtempSync(tmpdir() + sep);
  const resolved = resolve(
    __dirname,
    '../../../data/electionPrimaryPrecinctSplits/castVoteRecords'
  );
  fs.cpSync(resolved, tmpDir, { recursive: true });
  copiedDirectories.push(tmpDir);
  return tmpDir;
}

