import path from 'node:path';
// Generated by libs/fixture-generators script: pnpm generate-cvr-fixtures
import * as castVoteRecords from './castVoteRecords';

// Temporarily export everything other then toElectionPackage until toElectionPackage is formally deprecated
export {
  election,
  electionDefinition,
  asBuffer,
  asDataUrl,
  asFilePath,
  asText,
} from './electionGeneratedWithGridLayoutsMultiLang.json';

export * as electionPackage from './election-package-default-system-settings.zip';
// eslint-disable-next-line vx/gts-identifiers, camelcase
export * as baseElection_DEPRECATED from './electionBase.json';

export const castVoteRecordExport = {
  asDirectoryPath: () =>
    path.join(
      castVoteRecords.asDirectoryPath(),
      'machine_0000__2024-01-01_00-00-00'
    ),
} as const;
