import path from 'node:path';
// Generated by libs/fixture-generators script: pnpm generate-cvr-fixtures
import * as castVoteRecords from './castVoteRecords';

export * as electionPackageExport from './election-package-6431ece-4deca0d.zip';

export * from './electionBase.json';

// eslint-disable-next-line vx/gts-identifiers, camelcase
export * as baseElection_DEPRECATED from './electionBase.json';

export const castVoteRecordExport = {
  asDirectoryPath: () =>
    path.join(
      castVoteRecords.asDirectoryPath(),
      'machine_0000__2024-01-01_00-00-00'
    ),
} as const;
