import path from 'node:path';
// Generated by libs/fixture-generators script: pnpm generate-cvr-fixtures
import * as castVoteRecords from './castVoteRecords';

export * from './election.json';

export const castVoteRecordExport = {
  asDirectoryPath: () =>
    path.join(
      castVoteRecords.asDirectoryPath(),
      'machine_0000__2024-01-01_00-00-00'
    ),
} as const;
