/** Stub for 'jsdom' module, generated by script/build-stubs. DO NOT EDIT */
/* eslint-disable */
/* istanbul ignore file */

function __stubFnDoNotCall(): never {
  throw new Error('this function is a stub and should never be called');
}
/** Stub for JSDOM */
export const JSDOM = __stubFnDoNotCall;
/** Stub for VirtualConsole */
export const VirtualConsole = __stubFnDoNotCall;
/** Stub for CookieJar */
export const CookieJar = __stubFnDoNotCall;
/** Stub for ResourceLoader */
export const ResourceLoader = __stubFnDoNotCall;
/** Stub for toughCookie */
export const toughCookie = {
  version: "4.1.2",
  CookieJar: __stubFnDoNotCall,
  Cookie: __stubFnDoNotCall,
  Store: __stubFnDoNotCall,
  MemoryCookieStore: __stubFnDoNotCall,
  parseDate: __stubFnDoNotCall,
  formatDate: __stubFnDoNotCall,
  parse: __stubFnDoNotCall,
  fromJSON: __stubFnDoNotCall,
  domainMatch: __stubFnDoNotCall,
  defaultPath: __stubFnDoNotCall,
  pathMatch: __stubFnDoNotCall,
  getPublicSuffix: __stubFnDoNotCall,
  cookieCompare: __stubFnDoNotCall,
  permuteDomain: __stubFnDoNotCall,
  permutePath: __stubFnDoNotCall,
  canonicalDomain: __stubFnDoNotCall,
  PrefixSecurityEnum: {
    SILENT: "silent",
    STRICT: "strict",
    DISABLED: "unsafe-disabled",
  },
  ParameterError: __stubFnDoNotCall,
};
