import * as fs from 'fs';
import { join, relative } from 'path';
import { IO } from '../types';
import { createRequire } from 'module';

type Module = Record<PropertyKey, unknown>;

const stubFnName = '__stubFnDoNotCall';
const stubFnBody = `
function ${stubFnName}(): never {
  throw new Error('this function is a stub and should never be called');
}
`;

function writeValue(out: NodeJS.WritableStream, value: unknown): void {
  if (
    typeof value === 'string' ||
    typeof value === 'number' ||
    typeof value === 'boolean' ||
    value === null
  ) {
    out.write(JSON.stringify(value));
  } else if (value === undefined) {
    out.write('undefined');
  } else if (Array.isArray(value)) {
    out.write('[');
    for (const entry of value) {
      out.write('  ');
      writeValue(out, entry);
      out.write(',\n');
    }
    out.write(']');
  } else if (typeof value === 'object') {
    out.write('{\n');
    for (const [key, val] of Object.entries(value)) {
      out.write(`  ${key}: `);
      writeValue(out, val);
      out.write(',\n');
    }
    out.write('}');
  } else if (typeof value === 'function') {
    out.write(stubFnName);
  } else {
    throw new Error(`Unsupported value type: ${typeof value}`);
  }
}

function writeExports(out: NodeJS.WritableStream, obj: Module): void {
  for (const [key, value] of Object.entries(obj)) {
    out.write(`/** Stub for ${key} */\nexport const ${key} = `);
    writeValue(out, value);
    out.write(';\n');
  }
}

function writeStub(
  out: NodeJS.WritableStream,
  name: string,
  mod: Module
): void {
  out.write(
    `/** Stub for '${name}' module, generated by script/build-stubs. DO NOT EDIT */\n`
  );
  out.write('/* eslint-disable */\n');
  out.write(stubFnBody);
  writeExports(out, mod);
}

function buildStub(name: string, outputPath: string): void {
  const require = createRequire(join(process.cwd(), 'build-stubs.ts'));
  const mod = require(name);
  const out = fs.createWriteStream(outputPath);
  writeStub(out, name, mod);
}

function usage(out: NodeJS.WritableStream): void {
  out.write(`
  Usage: build-stubs <module>:<output-path> [<module>:<output-path> …]

  Example: build-stubs fs:src/stubs/fs.ts glob:src/stubs/glob.ts
  `);
}

export function main({ stdout, stderr }: IO) {
  for (let i = 2; i < process.argv.length; i += 1) {
    const arg = process.argv[i] as string;

    if (arg === '--help' || arg === '-h') {
      usage(stdout);
      process.exit(0);
      return;
    }

    if (arg.startsWith('-')) {
      stderr.write(`Unknown option: ${arg}\n`);
      usage(stderr);
      process.exit(1);
      return;
    }

    const [name, outputPath] = arg.split(':');

    if (!name || !outputPath) {
      stderr.write(`error: expected e.g. 'fs:src/stubs/fs.ts', got: ${arg}\n`);
      process.exit(1);
      return;
    }

    buildStub(name, outputPath);
  }
}
