version: 2.1

executors:
  nodejs:
    docker:
      - image: votingworks/cimg-debian12:4.1.0
        auth:
          username: $VX_DOCKER_USERNAME
          password: $VX_DOCKER_PASSWORD

workflows:
  test:
    jobs:
      - no-op

jobs:
  no-op:
    executor: nodejs
    resource_class: small
    steps:
      - run:
          name: noop
          command: |
            echo 0

