---

base_packages:
  - build-essential
  - curl
  - libsane 
  - libpng-dev 
  - libjpeg-dev 
  - libx11-dev 
  - libpixman-1-dev 
  - libcairo2-dev 
  - libpango1.0-dev 
  - libgif-dev 

svc_converter_ms_sems_packages:
  - python3.9 
  - python3.9-dev 
  - python3-distutils 
  - python3-pip

svc_smartcards_packages:
  - python3.9 
  - python3.9-dev 
  - python3.9-distutils 
  - python3-pip 
  - libusb-1.0-0-dev 
  - libpcsclite-dev 
  - pcscd 
  - pcsc-tools 
  - swig 

app_admin_packages:
  - fdisk 
  - dosfstools 
  - exfat-utils

app_central_scan_packages:
  - libsane 
  - libpng-dev 
  - libjpeg-dev 
  - libx11-dev 
  - libpixman-1-dev 
  - libcairo2-dev 
  - libpango1.0-dev 
  - libgif-dev

# No package dependencies yet
#app_mark_packages:

app_scan_packages:
  - libsane 
  - libpng-dev 
  - libjpeg-dev 
  - libx11-dev 
  - libpixman-1-dev 
  - libcairo2-dev 
  - libpango1.0-dev 
  - libgif-dev
