/* Generated by res-to-ts. DO NOT EDIT */
/* eslint-disable */
/* istanbul ignore file */

import { Buffer } from 'buffer';
import { mkdtempSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import { join, sep } from 'path';

/**
 * Data of data/systemSettings.json encoded as base64.
 *
 * SHA-256 hash of file data: 7daee9ac8834a414791cc7fe45a8754c27fc5e9886d956ba54de66e816431e4e
 */
const resourceDataBase64 = 'ewogICJhdXRoIjogewogICAgImFyZVBvbGxXb3JrZXJDYXJkUGluc0VuYWJsZWQiOiBmYWxzZSwKICAgICJpbmFjdGl2ZVNlc3Npb25UaW1lTGltaXRNaW51dGVzIjogMzAsCiAgICAibnVtSW5jb3JyZWN0UGluQXR0ZW1wdHNBbGxvd2VkQmVmb3JlQ2FyZExvY2tvdXQiOiA1LAogICAgIm92ZXJhbGxTZXNzaW9uVGltZUxpbWl0SG91cnMiOiAxMiwKICAgICJzdGFydGluZ0NhcmRMb2Nrb3V0RHVyYXRpb25TZWNvbmRzIjogMTUKICB9LAogICJtYXJrVGhyZXNob2xkcyI6IHsKICAgICJkZWZpbml0ZSI6IDAuMDcsCiAgICAibWFyZ2luYWwiOiAwLjA1LAogICAgIndyaXRlSW5UZXh0QXJlYSI6IDAuMDUKICB9LAogICJjZW50cmFsU2NhbkFkanVkaWNhdGlvblJlYXNvbnMiOiBbXSwKICAicHJlY2luY3RTY2FuQWRqdWRpY2F0aW9uUmVhc29ucyI6IFtdLAogICJwcmVjaW5jdFNjYW5EaXNhbGxvd0Nhc3RpbmdPdmVydm90ZXMiOiBmYWxzZSwKICAiY2FzdFZvdGVSZWNvcmRPcHRpbWl6YXRpb25FeGNsdWRlT3JpZ2luYWxTbmFwc2hvdHMiOiB0cnVlLAogICJjYXN0Vm90ZVJlY29yZE9wdGltaXphdGlvbkV4Y2x1ZGVSZWR1bmRhbnRNZXRhZGF0YSI6IHRydWUKfQo=';

/**
 * MIME type of data/systemSettings.json.
 */
export const mimeType = 'application/json';

/**
 * Path to a file containing this file's contents.
 *
 * SHA-256 hash of file data: 7daee9ac8834a414791cc7fe45a8754c27fc5e9886d956ba54de66e816431e4e
 */
export function asFilePath(): string {
  const directoryPath = mkdtempSync(tmpdir() + sep);
  const filePath = join(directoryPath, 'systemSettings.json');
  writeFileSync(filePath, asBuffer());
  return filePath;
}

/**
 * Convert to a `data:` URL of data/systemSettings.json, suitable for embedding in HTML.
 *
 * SHA-256 hash of file data: 7daee9ac8834a414791cc7fe45a8754c27fc5e9886d956ba54de66e816431e4e
 */
export function asDataUrl(): string {
  return `data:${mimeType};base64,${resourceDataBase64}`;
}

/**
 * Raw data of data/systemSettings.json.
 *
 * SHA-256 hash of file data: 7daee9ac8834a414791cc7fe45a8754c27fc5e9886d956ba54de66e816431e4e
 */
export function asBuffer(): Buffer {
  return Buffer.from(resourceDataBase64, 'base64');
}

/**
 * Text content of data/systemSettings.json.
 *
 * SHA-256 hash of file data: 7daee9ac8834a414791cc7fe45a8754c27fc5e9886d956ba54de66e816431e4e
 */
export function asText(): string {
  return asBuffer().toString('utf-8');
}