#!/usr/bin/env bash

set -euo pipefail

SCRIPTS_DIRECTORY="$(dirname "${BASH_SOURCE[0]}")"

VX_CERT_AUTHORITY_CERT_PATH="${SCRIPTS_DIRECTORY}/../certs/dev/vx-cert-authority-cert.pem" \
    VX_PRIVATE_KEY_PATH="${SCRIPTS_DIRECTORY}/../certs/dev/vx-private-key.pem" \
    "${SCRIPTS_DIRECTORY}/configure-java-card"
