#!/usr/bin/env bash

set -euo pipefail

SCRIPTS_DIRECTORY="$(dirname "${BASH_SOURCE[0]}")"

rm -r "${SCRIPTS_DIRECTORY}/../certs/test"

echo -n 'Generating keys and certs in libs/auth/certs/test/set-1... '
"${SCRIPTS_DIRECTORY}/generate-dev-keys-and-certs" \
    --for-tests --output-dir "${SCRIPTS_DIRECTORY}/../certs/test/set-1"

echo -n 'Generating keys and certs in libs/auth/certs/test/set-2... '
"${SCRIPTS_DIRECTORY}/generate-dev-keys-and-certs" \
    --for-tests --output-dir "${SCRIPTS_DIRECTORY}/../certs/test/set-2"
