#!/usr/bin/env bash

set -euo pipefail

rm -r ./certs/test

echo -n 'Generating keys and certs in ./certs/test/set-1... '
FOR_TESTS=true \
OUTPUT_DIR=./certs/test/set-1 \
./scripts/generate-dev-keys-and-certs

echo -n 'Generating keys and certs in ./certs/test/set-2... '
FOR_TESTS=true \
OUTPUT_DIR=./certs/test/set-2 \
./scripts/generate-dev-keys-and-certs
