export const PRECINCT_SCANNER_STATES = [
  'connecting',
  'disconnected',
  'no_paper',
  'hardware_ready_to_scan',
  'scanning',
  'returning_to_rescan',
  'ready_to_accept',
  'accepting',
  'accepted',
  'needs_review',
  'accepting_after_review',
  'returning',
  'returned',
  'rejecting',
  'rejected',
  'jammed',
  'cover_open',
  'both_sides_have_paper',
  'recovering_from_error',
  'double_sheet_jammed',
  'unrecoverable_error',
  'paused',
  'calibrating_double_feed_detection.double_sheet',
  'calibrating_double_feed_detection.single_sheet',
  'calibrating_double_feed_detection.done',
] as const;

export type PrecinctScannerState = (typeof PRECINCT_SCANNER_STATES)[number];
