export const CARD_LONG_VALUE_WRITE_DELAY = 1000;
export const BALLOT_PRINTING_TIMEOUT_SECONDS = 5;
export const BALLOT_INSTRUCTIONS_TIMEOUT_SECONDS = 30;
export const REPORT_PRINTING_TIMEOUT_SECONDS = 4;
export const CHECK_ICON = '✓';
export const WRITE_IN_CANDIDATE_MAX_LENGTH = 40;
export const QUIT_KIOSK_IDLE_SECONDS = 5 * 60; // 5 minutes
export const SECURITY_PIN_LENGTH = 6;
