
const all = [
  { regular: 'a', ipa: 'æ', 'x-sampa': '{', exampleWord: 'cat', exampleIpa: 'ˈkæt', exampleXsampa: '"k{t', isConsonant: false },
  { regular: 'ah', ipa: 'ɑː', 'x-sampa': 'A:', exampleWord: 'cot', exampleIpa: 'ˈkɑːt', exampleXsampa: '"kA:t', isConsonant: false },
  { regular: 'au', ipa: 'ɔː', 'x-sampa': 'O:', exampleWord: 'more', exampleIpa: 'ˈmɔːɹ', exampleXsampa: '"mO:r\\', isConsonant: false },
  { regular: 'ay', ipa: 'eɪ', 'x-sampa': 'eI', exampleWord: 'shade', exampleIpa: 'ˈʃeɪd', exampleXsampa: '"SeId', isConsonant: false },
  { regular: 'aye', ipa: 'aɪ', 'x-sampa': 'aI', exampleWord: 'price', exampleIpa: 'ˈpɹaɪs', exampleXsampa: '"pr\\aIs', isConsonant: false },
  { regular: 'b', ipa: 'b', 'x-sampa': 'b', exampleWord: 'bubble', exampleIpa: 'ˈbʌbəl', exampleXsampa: '"bVb@l', isConsonant: true },
  { regular: 'ch', ipa: 'ʧ', 'x-sampa': 'tS', exampleWord: 'changed', exampleIpa: 'ˈʧeɪnʤd', exampleXsampa: '"tSeIndZd', isConsonant: true },
  { regular: 'd', ipa: 'd', 'x-sampa': 'd', exampleWord: 'dog', exampleIpa: 'ˈdɑːg', exampleXsampa: '"dA:g', isConsonant: true },
  { regular: 'ee', ipa: 'iː', 'x-sampa': 'i:', exampleWord: 'unique', exampleIpa: 'ˌjuːˈniːk', exampleXsampa: '%ju:"ni:k', isConsonant: false },
  { regular: 'eh', ipa: 'ɛ', 'x-sampa': 'E', exampleWord: 'bed', exampleIpa: 'ˈbɛd', exampleXsampa: '"bEd', isConsonant: false },
  { regular: 'f', ipa: 'f', 'x-sampa': 'f', exampleWord: 'frog', exampleIpa: 'ˈfɹɑːg', exampleXsampa: '"fr\\A:g', isConsonant: true },
  { regular: 'g', ipa: 'ɡ', 'x-sampa': 'g', exampleWord: 'gravely', exampleIpa: 'ˈgɹeɪˌvliː', exampleXsampa: '"gr\\eI%vli:', isConsonant: true },
  { regular: 'h', ipa: 'h', 'x-sampa': 'h', exampleWord: 'mahogany', exampleIpa: 'məˈhɑːgəˌniː', exampleXsampa: 'm@"hA:g@%ni:', isConsonant: true },
  { regular: 'i', ipa: 'ɪ', 'x-sampa': 'I', exampleWord: 'kit', exampleIpa: 'ˈkɪt', exampleXsampa: '"kIt', isConsonant: false },
  { regular: 'ir', ipa: 'ɚ', 'x-sampa': '@`', exampleWord: 'bird', exampleIpa: 'ˈbɚd', exampleXsampa: '"b@`d', isConsonant: false },
  { regular: 'j', ipa: 'ʤ', 'x-sampa': 'dZ', exampleWord: 'magenta', exampleIpa: 'məˈʤɛntə', exampleXsampa: 'm@"dZEnt@', isConsonant: true },
  { regular: 'k', ipa: 'k', 'x-sampa': 'k', exampleWord: 'crown', exampleIpa: 'ˈkɹaʊn', exampleXsampa: '"kr\\aUn', isConsonant: true },
  { regular: 'l', ipa: 'l', 'x-sampa': 'l', exampleWord: 'lately', exampleIpa: 'ˈleɪtˌliː', exampleXsampa: '"leIt%li:', isConsonant: true },
  { regular: 'm', ipa: 'm', 'x-sampa': 'm', exampleWord: 'mapping', exampleIpa: 'ˈmæpəŋ', exampleXsampa: '"m{p@N', isConsonant: true },
  { regular: 'n', ipa: 'n', 'x-sampa': 'n', exampleWord: 'nine', exampleIpa: 'ˈnaɪn', exampleXsampa: '"naIn', isConsonant: true },
  { regular: 'ng', ipa: 'ŋ', 'x-sampa': 'N', exampleWord: 'bank', exampleIpa: 'ˈbæŋk', exampleXsampa: '"b{Nk', isConsonant: true },
  { regular: 'oa', ipa: 'oʊ', 'x-sampa': 'oU', exampleWord: 'boat', exampleIpa: 'ˈboʊt', exampleXsampa: '"boUt', isConsonant: false },
  { regular: 'oi', ipa: 'ɔɪ', 'x-sampa': 'OI', exampleWord: 'choice', exampleIpa: 'ˈʧɔɪs', exampleXsampa: '"tSOIs', isConsonant: false },
  { regular: 'oo', ipa: 'uː', 'x-sampa': 'u:', exampleWord: 'school', exampleIpa: 'ˈskuːl', exampleXsampa: '"sku:l', isConsonant: false },
  { regular: 'ow', ipa: 'aʊ', 'x-sampa': 'aU', exampleWord: 'flower', exampleIpa: 'ˈflaʊɚ', exampleXsampa: '"flaU@`', isConsonant: false },
  { regular: 'p', ipa: 'p', 'x-sampa': 'p', exampleWord: 'popular', exampleIpa: 'ˈpɑːpjəlɚ', exampleXsampa: '"pA:pj@l@`', isConsonant: true },
  { regular: 'r', ipa: 'ɹ', 'x-sampa': 'r\\', exampleWord: 'roaring', exampleIpa: 'ˈɹɔːɹəŋ', exampleXsampa: '"r\\O:r\\@N', isConsonant: true },
  { regular: 's', ipa: 's', 'x-sampa': 's', exampleWord: 'massage', exampleIpa: 'məˈsɑːʒ', exampleXsampa: 'm@"sA:Z', isConsonant: true },
  { regular: 'sh', ipa: 'ʃ', 'x-sampa': 'S', exampleWord: 'shopping', exampleIpa: 'ˈʃɑːpəŋ', exampleXsampa: '"SA:p@N', isConsonant: true },
  { regular: 'szh', ipa: 'ʒ', 'x-sampa': 'Z', exampleWord: 'leisure', exampleIpa: 'ˈliːʒɚ', exampleXsampa: '"li:Z@', isConsonant: true },
  { regular: 't', ipa: 't', 'x-sampa': 't', exampleWord: 'tinker', exampleIpa: 'ˈtɪŋkɚ', exampleXsampa: '"tINk@`', isConsonant: true },
  { regular: 'th', ipa: 'ð', 'x-sampa': 'D', exampleWord: 'mother', exampleIpa: 'ˈmʌðɚ', exampleXsampa: '"mVD@`', isConsonant: true },
  { regular: 'thh', ipa: 'θ', 'x-sampa': 'T', exampleWord: 'thigh', exampleIpa: 'ˈθaɪ', exampleXsampa: '"TaI', isConsonant: true },
  { regular: 'ou', ipa: 'ʊ', 'x-sampa': 'U', exampleWord: 'could', exampleIpa: 'ˈkʊd', exampleXsampa: '"kUd', isConsonant: false },
  { regular: 'u', ipa: 'ʌ', 'x-sampa': 'V', exampleWord: 'pulse', exampleIpa: 'ˈpʌls', exampleXsampa: '"pVls', isConsonant: false },
  { regular: 'uh', ipa: 'ə', 'x-sampa': '@', exampleWord: 'again', exampleIpa: 'əˈgɛn', exampleXsampa: '@"gEn', isConsonant: false },
  { regular: 'v', ipa: 'v', 'x-sampa': 'v', exampleWord: 'valve', exampleIpa: 'ˈvælv', exampleXsampa: '"v{lv', isConsonant: true },
  { regular: 'w', ipa: 'w', 'x-sampa': 'w', exampleWord: 'whirlwind', exampleIpa: 'ˈwɚlˌwɪnd', exampleXsampa: '"w@`l%wInd', isConsonant: true },
  { regular: 'y', ipa: 'j', 'x-sampa': 'j', exampleWord: 'younger', exampleIpa: 'ˈjʌŋgɚ', exampleXsampa: '"jVNg@`', isConsonant: true },
  { regular: 'z', ipa: 'z', 'x-sampa': 'z', exampleWord: 'zoom', exampleIpa: 'ˈzuːm', exampleXsampa: '"zu:m', isConsonant: true },
] as const;

export const phonemes = {
  en: {
    all,
    consonants: all.filter(p => p.isConsonant),
    stresses: {
      primary: {regular: "ˈ", ipa: "ˈ", 'x-sampa': '"'},
      secondary: {regular: "ˌ", ipa: "ˌ", 'x-sampa': "%"},
    },
    vowels: all.filter(p => !p.isConsonant),
  },
} as const;
