/* Generated by res-to-ts. DO NOT EDIT */
/* eslint-disable */
/* istanbul ignore file */

import { Buffer } from 'buffer';
import { mkdtempSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import { join, sep } from 'path';

/**
 * Data of data/electionMinimalExhaustiveSample/ballot-package.zip encoded as base64.
 *
 * SHA-256 hash of file data: 40dac33414cbf9cf133de426d2033b4cad15991ae6484ffdfc0149d7d2790662
 */
const resourceDataBase64 = 'UEsDBBQAAAgIAExqilaC2UmW5QMAAIQTAAANAC0AZWxlY3Rpb24uanNvblVUBQABEW80ZAoAIAAAAAAAAQAYAACopZrpa9kBAKilmulr2QEAqKWa6WvZAe1YW3PaOBR+z68442fcAn3Z7csObWHDbAIMsLuzbfMgGwGayJJXkpM6mfz3SrLxBcsuJU33ZTOEEf4O5zuXTxf0eAHgKaIo9t6CN/6CophiWAgSIZHCmOJQEc68njGTCilrtjID4FtYWfMMDXnCVKrhR/1JfyYbYyqthZ+DvQxiKMr8ZGzvM1BjT9bTJqcZ9ocDv/+r3/9l3e+/tS891u8ZYYAo5eoKpTxRJW2MYixW5MF6oFgpLCqeiVSChEpq8JO1z75VhHsw8Ad5rJVoP+QYDDwLPen3G+s2RkIR3Oq03/R1jaII0fL5NqF0VsNgoZ2mpQUKAoHvMjzn77nIHIFPiNy7qQzSTjQ5zjPkTGHZXr1Agz5iWjvUj44yPFR22lpnlcY2qBCxDbEaKKGDQN9pBhhZhhKVGNmYBsUT05B0elz8wnGZgPl7LEZFInsuZElvgUMxL5tQzma9ar6bAnvqdZFwq00nybwJnUmy5V/cFJNjoJ0gH92UEtET7/5vQRSeMmO/RVTiTCtOTVZ1sa2J8b9SRYXgdFVojx3CWDnRWlUHJ7dNIhrly26BlKtmE2uneXbzHji3y3dIXmpSf+Tc7gGaodm+Nz9sUj/gQCB3ST82oTPnGyVtbbtqIGdS3CK2Q4JzN80fTvRMKkxxvEdMuanGTvQZ64gSSZcS0b8JEiSJCjm+xFrSKcbhD1tLIl035AuUukt7bWBYHsNnriZxst1iUauWRQ9sixb8TDrBw9t2sqUTPZNKt3i360pt3WbwjBXzGzJl+N43iyYmal/Zxb9DnymWjFceF/ucPfHCNUYyERgq39xgGQoS27O6NpwyoghS5A4XxjP+CgbDHqz2PKEbOBy9iUpB754ooOYoiEAHDxJt9TzzpUq1hc4EQi4VYTst/36/b/5/+8w+MxhRfUphdZrBEEYnkSiBNsTEq4+6VY5BwVFmp+sxP+RWisBZbh/FseB3eFPptkdRgKmxncyXMFoslvO/Rlcwn8B4ur4cL6FSrqxMYOwq2TUNRl7uvtCnx/i3g2SnRDn6fTSdrdbwbr6+dFHPPrSWvojqBH3GJLz9X50/SZ1Z1K2ibHT5PHlVwm7Xv6MuDVF3yMcspboUL6icN63KyTuXhwABhgAxhjdAGGgfEJpe8nvzhKJbLEHvxyB0pkKe2jDt0D9OsVrCf8ar7+uN3T06Xc7mR3W/KC4WBA4J67ivOBi47isWOVbcVzjbWXgYdngYHt8EZHcvKzMHW2MbXJcea4nUoq5FUO65tZuaqqhKk9rvgY4Mh5OfFkfjZkgfHOmfwnb5tRnL19mq4+tfi/SVvNt5F08XXwFQSwMEFAAACAgATGqKVoIFQ+ctAAAAKwAAABMALQBzeXN0ZW1TZXR0aW5ncy5qc29uVVQFAAERbzRkCgAgAAAAAAABABgAEEComulr2QEQQKia6WvZARBAqJrpa9kBq+ZSUFBKLEoNyM/JCc8vyk4tck4sSgnIzCt2zUtMyklNUbJSSEvMKU7lqgUAUEsBAhQAFAAACAgATGqKVoLZSZblAwAAhBMAAA0ALQAAAAAAAAAAAAAAAAAAAGVsZWN0aW9uLmpzb25VVAUAARFvNGQKACAAAAAAAAEAGAAAqKWa6WvZAQCopZrpa9kBAKilmulr2QFQSwECFAAUAAAICABMaopWggVD5y0AAAArAAAAEwAtAAAAAAAAAAAAAAA9BAAAc3lzdGVtU2V0dGluZ3MuanNvblVUBQABEW80ZAoAIAAAAAAAAQAYABBAqJrpa9kBEEComulr2QEQQKia6WvZAVBLBQYAAAAAAgACANYAAADIBAAAAAA=';

/**
 * MIME type of data/electionMinimalExhaustiveSample/ballot-package.zip.
 */
export const mimeType = 'application/zip';

/**
 * Path to a file containing this file's contents.
 *
 * SHA-256 hash of file data: 40dac33414cbf9cf133de426d2033b4cad15991ae6484ffdfc0149d7d2790662
 */
export function asFilePath(): string {
  const directoryPath = mkdtempSync(tmpdir() + sep);
  const filePath = join(directoryPath, 'ballot-package.zip');
  writeFileSync(filePath, asBuffer());
  return filePath;
}

/**
 * Convert to a `data:` URL of data/electionMinimalExhaustiveSample/ballot-package.zip, suitable for embedding in HTML.
 *
 * SHA-256 hash of file data: 40dac33414cbf9cf133de426d2033b4cad15991ae6484ffdfc0149d7d2790662
 */
export function asDataUrl(): string {
  return `data:${mimeType};base64,${resourceDataBase64}`;
}

/**
 * Raw data of data/electionMinimalExhaustiveSample/ballot-package.zip.
 *
 * SHA-256 hash of file data: 40dac33414cbf9cf133de426d2033b4cad15991ae6484ffdfc0149d7d2790662
 */
export function asBuffer(): Buffer {
  return Buffer.from(resourceDataBase64, 'base64');
}