/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Asks the kernel to drop the page cache for an open file, via
 * `posix_fadvise(2)` with `POSIX_FADV_DONTNEED` over the whole file.
 *
 * # Errors
 *
 * Fails with the syscall's errno, e.g. `EBADF` if `fd` is not an open file
 * descriptor.
 */
export declare function fadviseDontNeed(fd: number): void

/**
 * Takes an exclusive advisory lock on an open file without waiting, via
 * `flock(2)` with `LOCK_EX | LOCK_NB`. The kernel drops the lock when the
 * descriptor closes, including when the process holding it dies, so a lock
 * can never be left stranded by a crash.
 *
 * # Errors
 *
 * Fails with the syscall's errno: `EWOULDBLOCK` (reported as `EAGAIN`) when
 * another open file description already holds the lock, or `EBADF` if `fd` is
 * not an open file descriptor.
 */
export declare function flockExclusiveNonblocking(fd: number): void

/**
 * Atomically exchanges two paths using `renameat2(2)` with `RENAME_EXCHANGE`.
 * Both paths must exist; at no point during the call does either name not
 * exist.
 *
 * # Errors
 *
 * Fails with the syscall's errno, e.g. `ENOENT` if either path does not
 * exist, or `EINVAL` on a filesystem without `RENAME_EXCHANGE` support.
 */
export declare function renameExchange(oldPath: string, newPath: string): void

/**
 * Renames a path using `renameat2(2)` with `RENAME_NOREPLACE`: fails with
 * `EEXIST` if `new_path` exists, where a plain `rename(2)` would replace it.
 *
 * # Errors
 *
 * Fails with the syscall's errno, e.g. `EEXIST` if `new_path` exists.
 */
export declare function renameNoReplace(oldPath: string, newPath: string): void

/**
 * Flushes the filesystem containing the file referred to by `fd`, via
 * `syncfs(2)`: all of that filesystem's dirty data and metadata is written to
 * the device before this returns.
 *
 * # Errors
 *
 * Fails with the syscall's errno, e.g. `EBADF` if `fd` is not an open file
 * descriptor, or `EIO` if writing the data back failed.
 */
export declare function syncfs(fd: number): void
