/* Generated by res-to-ts. DO NOT EDIT */
/* eslint-disable */
/* istanbul ignore file */

import { Buffer } from 'node:buffer';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, sep } from 'node:path';

/**
 * Data of data/electionTwoPartyPrimary/precinctScannerCardTallies/votingPausedAllPrecincts.json encoded as base64.
 *
 * SHA-256 hash of file data: 388bbdd36b122a6325525d50dd36f3810bb0b8a7523b1b7b1079934b5423121d
 */
const resourceDataBase64 = 'ewogICJ0YWxseU1hY2hpbmVUeXBlIjogInByZWNpbmN0X3NjYW5uZXIiLAogICJ0b3RhbEJhbGxvdHNTY2FubmVkIjogOTcsCiAgImlzTGl2ZU1vZGUiOiBmYWxzZSwKICAicG9sbHNUcmFuc2l0aW9uIjogInBhdXNlX3ZvdGluZyIsCiAgIm1hY2hpbmVJZCI6ICIwMDAwIiwKICAidGltZVNhdmVkIjogMTY2NTYxNjA2OTc2OSwKICAidGltZVBvbGxzVHJhbnNpdGlvbmVkIjogMTY2NTYxNjA2OTc2OSwKICAicHJlY2luY3RTZWxlY3Rpb24iOiB7CiAgICAia2luZCI6ICJBbGxQcmVjaW5jdHMiCiAgfQp9Cg==';

/**
 * MIME type of data/electionTwoPartyPrimary/precinctScannerCardTallies/votingPausedAllPrecincts.json.
 */
export const mimeType = 'application/json';

/**
 * Path to a file containing this file's contents.
 *
 * SHA-256 hash of file data: 388bbdd36b122a6325525d50dd36f3810bb0b8a7523b1b7b1079934b5423121d
 */
export function asFilePath(): string {
  const directoryPath = mkdtempSync(tmpdir() + sep);
  const filePath = join(directoryPath, 'votingPausedAllPrecincts.json');
  writeFileSync(filePath, asBuffer());
  return filePath;
}

/**
 * Convert to a `data:` URL of data/electionTwoPartyPrimary/precinctScannerCardTallies/votingPausedAllPrecincts.json, suitable for embedding in HTML.
 *
 * SHA-256 hash of file data: 388bbdd36b122a6325525d50dd36f3810bb0b8a7523b1b7b1079934b5423121d
 */
export function asDataUrl(): string {
  return `data:${mimeType};base64,${resourceDataBase64}`;
}

/**
 * Raw data of data/electionTwoPartyPrimary/precinctScannerCardTallies/votingPausedAllPrecincts.json.
 *
 * SHA-256 hash of file data: 388bbdd36b122a6325525d50dd36f3810bb0b8a7523b1b7b1079934b5423121d
 */
export function asBuffer(): Buffer {
  return Buffer.from(resourceDataBase64, 'base64');
}

/**
 * Text content of data/electionTwoPartyPrimary/precinctScannerCardTallies/votingPausedAllPrecincts.json.
 *
 * SHA-256 hash of file data: 388bbdd36b122a6325525d50dd36f3810bb0b8a7523b1b7b1079934b5423121d
 */
export function asText(): string {
  return asBuffer().toString('utf-8');
}