/* Generated by res-to-ts. DO NOT EDIT */
/* eslint-disable */
/* istanbul ignore file */

import { Buffer } from 'node:buffer';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, sep } from 'node:path';

/**
 * Data of data/electionTwoPartyPrimary/precinctScannerCardTallies/votingResumedAllPrecincts.json encoded as base64.
 *
 * SHA-256 hash of file data: c76d279277fb33af41c7f2f72f0eef1391d77b3dec3cff56c531507ebe76994a
 */
const resourceDataBase64 = 'ewogICJ0YWxseU1hY2hpbmVUeXBlIjogInByZWNpbmN0X3NjYW5uZXIiLAogICJ0b3RhbEJhbGxvdHNTY2FubmVkIjogOTcsCiAgImlzTGl2ZU1vZGUiOiBmYWxzZSwKICAicG9sbHNUcmFuc2l0aW9uIjogInJlc3VtZV92b3RpbmciLAogICJtYWNoaW5lSWQiOiAiMDAwMCIsCiAgInRpbWVTYXZlZCI6IDE2NjU2MTc1NTM4NTEsCiAgInRpbWVQb2xsc1RyYW5zaXRpb25lZCI6IDE2NjU2MTc1NTM4NTEsCiAgInByZWNpbmN0U2VsZWN0aW9uIjogewogICAgImtpbmQiOiAiQWxsUHJlY2luY3RzIgogIH0KfQo=';

/**
 * MIME type of data/electionTwoPartyPrimary/precinctScannerCardTallies/votingResumedAllPrecincts.json.
 */
export const mimeType = 'application/json';

/**
 * Path to a file containing this file's contents.
 *
 * SHA-256 hash of file data: c76d279277fb33af41c7f2f72f0eef1391d77b3dec3cff56c531507ebe76994a
 */
export function asFilePath(): string {
  const directoryPath = mkdtempSync(tmpdir() + sep);
  const filePath = join(directoryPath, 'votingResumedAllPrecincts.json');
  writeFileSync(filePath, asBuffer());
  return filePath;
}

/**
 * Convert to a `data:` URL of data/electionTwoPartyPrimary/precinctScannerCardTallies/votingResumedAllPrecincts.json, suitable for embedding in HTML.
 *
 * SHA-256 hash of file data: c76d279277fb33af41c7f2f72f0eef1391d77b3dec3cff56c531507ebe76994a
 */
export function asDataUrl(): string {
  return `data:${mimeType};base64,${resourceDataBase64}`;
}

/**
 * Raw data of data/electionTwoPartyPrimary/precinctScannerCardTallies/votingResumedAllPrecincts.json.
 *
 * SHA-256 hash of file data: c76d279277fb33af41c7f2f72f0eef1391d77b3dec3cff56c531507ebe76994a
 */
export function asBuffer(): Buffer {
  return Buffer.from(resourceDataBase64, 'base64');
}

/**
 * Text content of data/electionTwoPartyPrimary/precinctScannerCardTallies/votingResumedAllPrecincts.json.
 *
 * SHA-256 hash of file data: c76d279277fb33af41c7f2f72f0eef1391d77b3dec3cff56c531507ebe76994a
 */
export function asText(): string {
  return asBuffer().toString('utf-8');
}