import moment from 'moment'

const SECTION_SEPARATOR = '__'
const SUBSECTION_SEPARATOR = '_'
const WORD_SEPARATOR = '-'
const TIME_FORMAT_STRING = `YYYY${WORD_SEPARATOR}MM${WORD_SEPARATOR}DD${SUBSECTION_SEPARATOR}HH${WORD_SEPARATOR}mm${WORD_SEPARATOR}ss`

export const BALLOT_PACKAGE_FOLDER = 'ballot-packages'

export type ElectionData = {
  electionCounty: string
  electionName: string
  electionHash: string
  timestamp: Date
}

/**
 * Convert an autogenerated name of the ballot configuration package zip archive
 * to the pieces of data contained in the name.
 */
export function parseBallotExportPackageInfoFromFilename(
  filename: string
): ElectionData | undefined {
  // There should be two underscores seperating the timestamp from the election information
  const segments = filename.split(SECTION_SEPARATOR)
  if (segments.length !== 2) {
    return
  }

  const [electionString, timeString] = segments

  let electionSegments = electionString.split(SUBSECTION_SEPARATOR)
  if (electionSegments.length !== 3) {
    return
  }
  electionSegments = electionSegments.map((s) => s.replace(/-/g, ' '))
  const [electionCounty, electionName, electionHash] = electionSegments

  const parsedTime = moment(timeString, TIME_FORMAT_STRING)
  return {
    electionCounty,
    electionName,
    electionHash,
    timestamp: parsedTime.toDate(),
  }
}
