#!/usr/bin/env bash

set -euo pipefail

local_user=`logname`
local_user_home_dir=$( getent passwd "${local_user}" | cut -d: -f6 )

# Make sure PATH includes cargo and /sbin
export PATH="${local_user_home_dir}/.cargo/bin:${PATH}:/sbin/"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

for app in ${DIR}/../apps/*/frontend ${DIR}/../apps/*/backend; do
  if [ -d "${app}" ]; then
    make -C "${app}" bootstrap
  fi
done

pnpm --dir "${DIR}/.." install
