#!/usr/bin/env bash

set -euo pipefail

#-- Ansible for all packages, then make build?

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
echo $DIR

for app in ${DIR}/../services/* ${DIR}/../apps/*/frontend ${DIR}/../apps/*/backend; do
  if [ -d "${app}" ]; then
    echo $app
    #make -C "${app}" bootstrap
  fi
done

echo "${DIR}/.."
#pnpm --dir "${DIR}/.." install
