#!/usr/bin/env bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

for app in ${DIR}/../frontends/* ${DIR}/../apps/*/frontend ${DIR}/../apps/*/backend; do
  if [ -d "${app}" ]; then
    make -C "${app}" bootstrap
  fi
done

pnpm --dir "${DIR}/.." install
