#!/usr/bin/env node

// @ts-check

require('esbuild-runner').install({
  type: 'transform',
});

require('./src/build-stubs').main({
  stdin: process.stdin,
  stdout: process.stdout,
  stderr: process.stderr,
});
