#!/usr/bin/env node

import { main } from './src/parameter-properties-codemod/cli.ts';

try {
  process.exitCode = main(process.argv.slice(2), {
    stdin: process.stdin,
    stdout: process.stdout,
    stderr: process.stderr,
  });
} catch (error) {
  console.error(error.stack);
  process.exitCode = 1;
}
