#!/usr/bin/env node

// @ts-check

const { join } = require('path')

require('ts-node').register({
  transpileOnly: true,
  project: join(__dirname, 'tsconfig.json'),
})

require('./src/prod-build').main({
  stdin: process.stdin,
  stdout: process.stdout,
  stderr: process.stderr,
})
