#!/usr/bin/env node

// @ts-check

require('esbuild-runner').install({
  type: 'transform',
});

try {
  process.exitCode = require('./src/prune-turbo-cache/cli').main({
    stdin: process.stdin,
    stdout: process.stdout,
    stderr: process.stderr,
  });
} catch (error) {
  console.error(error.stack);
  process.exitCode = 1;
}
