#!/usr/bin/env node

import { main } from './src/prune-turbo-cache/cli.ts';

try {
  process.exitCode = main({
    stdin: process.stdin,
    stdout: process.stdout,
    stderr: process.stderr,
  });
} catch (error) {
  console.error(error.stack);
  process.exitCode = 1;
}
