#!/usr/bin/env node

import { main } from './src/run-dev/index.ts';

try {
  process.exitCode = await main(process.argv, {
    stdout: process.stdout,
    stderr: process.stderr,
  });
} catch (error) {
  console.error(error.stack);
  process.exit(1);
}
