#!/usr/bin/env node

// @ts-check

require('esbuild-runner/register');

require('./src/run-dev')
  .main(process.argv, {
    stdout: process.stdout,
    stderr: process.stderr,
  })
  .then((exitCode) => {
    process.exitCode = exitCode;
  })
  .catch((error) => {
    console.error(error.stack);
    process.exit(1);
  });
