#!/usr/bin/env bash

# This used to install node and other dependencies.
# That functionality has been migrated to Ansible.
# This script now simply calls that functionality.

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${DIR}/../ansible"

sudo ansible-playbook playbooks/setup-node.yaml

cd $DIR

exit 0

