import { afterAll, beforeEach, expect, test, vi } from 'vitest';
import { Buffer } from 'node:buffer';
import JsZip from 'jszip';
import get from 'lodash.get';
import {
  DateWithoutTime,
  assert,
  assertDefined,
  find,
} from '@votingworks/basics';
import { readFileSync } from 'node:fs';
import {
  electionFamousNames2021Fixtures,
  electionPrimaryPrecinctSplitsFixtures,
  readElectionTwoPartyPrimaryDefinition,
} from '@votingworks/fixtures';
import {
  AdjudicationReason,
  HmpbBallotPaperSize,
  BallotType,
  CandidateContest,
  DEFAULT_SYSTEM_SETTINGS,
  Election,
  ElectionStringKey,
  SystemSettings,
  UiStringsPackage,
  formatBallotHash,
  formatElectionPackageHash,
  mergeUiStrings,
  LanguageCode,
  getAllBallotLanguages,
  ElectionPackageFileName,
  unsafeParse,
  ElectionIdSchema,
  DistrictIdSchema,
} from '@votingworks/types';
import {
  BooleanEnvironmentVariableName,
  getBallotStylesByPrecinctId,
  getEntries,
  getFeatureFlagMock,
  getFileByName,
  openZip,
  readJsonEntry,
} from '@votingworks/utils';
import {
  forEachUiString,
  isMockCloudSynthesizedSpeech,
  mockCloudTranslatedText,
  readElectionPackageFromFile,
} from '@votingworks/backend';
import {
  countObjectLeaves,
  getObjectLeaves,
  suppressingConsoleOutput,
} from '@votingworks/test-utils';
import {
  allBaseBallotProps,
  BallotMode,
  ballotTemplates,
  BaseBallotProps,
  hmpbStringsCatalog,
  renderAllBallotsAndCreateElectionDefinition,
  RenderDocument,
} from '@votingworks/hmpb';
import {
  ELECTION_PACKAGE_FILE_NAME_REGEX,
  exportElectionPackage,
  processNextBackgroundTaskIfAny,
  testSetupHelpers,
} from '../test/helpers';
import { FULL_TEST_DECK_TALLY_REPORT_FILE_NAME } from './test_decks';
import {
  BallotOrderInfo,
  BallotStyle,
  Precinct,
  PrecinctWithSplits,
  PrecinctWithoutSplits,
  User,
  convertToVxfBallotStyle,
  hasSplits,
} from './types';
import { generateBallotStyles } from './ballot_styles';
import { ElectionRecord } from '.';
import { ElectionPackage, getTempBallotLanguageConfigsForCert } from './store';
import { renderBallotStyleReadinessReport } from './ballot_style_reports';
import { BALLOT_STYLE_READINESS_REPORT_FILE_NAME } from './app';

vi.setConfig({
  testTimeout: 60_000,
});

const vxUser: User = {
  orgId: 'votingworks',
  isVotingWorksUser: true,
};

const nonVxUser: User = {
  orgId: '123',
  isVotingWorksUser: false,
};

const mockFeatureFlagger = getFeatureFlagMock();

vi.mock(import('@votingworks/utils'), async (importActual) => ({
  ...(await importActual()),
  isFeatureFlagEnabled: (flag) => mockFeatureFlagger.isEnabled(flag),
}));

vi.mock('./ballot_style_reports.js');

const { setupApp, cleanup } = testSetupHelpers();

const MOCK_READINESS_REPORT_CONTENTS = '%PDF - MockReadinessReport';
const MOCK_READINESS_REPORT_PDF = Buffer.from(
  MOCK_READINESS_REPORT_CONTENTS,
  'utf-8'
);

function expectedEnglishBallotStrings(election: Election): UiStringsPackage {
  const expectedStrings = mergeUiStrings(election.ballotStrings, {
    [LanguageCode.ENGLISH]: hmpbStringsCatalog,
  });
  // Ballot style IDs are generated by VxDesign and then translated
  expectedStrings[LanguageCode.ENGLISH]!['ballotStyleId'] = Object.fromEntries(
    election.ballotStyles.map(({ id, groupId }) => [id, groupId])
  );
  return expectedStrings;
}

afterAll(cleanup);

beforeEach(() => {
  mockFeatureFlagger.resetFeatureFlags();
  mockFeatureFlagger.enableFeatureFlag(
    BooleanEnvironmentVariableName.ENABLE_CLOUD_TRANSLATION_AND_SPEECH_SYNTHESIS
  );

  vi.mocked(renderBallotStyleReadinessReport).mockResolvedValue(
    MOCK_READINESS_REPORT_PDF
  );
});

test('CRUD elections', async () => {
  const { apiClient } = await setupApp();
  expect(await apiClient.listElections({ user: vxUser })).toEqual([]);

  const expectedElectionId = unsafeParse(ElectionIdSchema, 'election-1');
  const electionId = (
    await apiClient.createElection({
      id: expectedElectionId,
      user: vxUser,
      orgId: nonVxUser.orgId,
    })
  ).unsafeUnwrap();
  expect(electionId).toEqual(expectedElectionId);

  const election = await apiClient.getElection({ electionId, user: vxUser });
  // New elections should be blank
  expect(election).toEqual<ElectionRecord>({
    orgId: nonVxUser.orgId,
    election: {
      id: expectedElectionId,
      ballotLayout: {
        metadataEncoding: 'qr-code',
        paperSize: HmpbBallotPaperSize.Letter,
      },
      ballotStyles: [],
      contests: [],
      county: {
        id: 'county-id',
        name: '',
      },
      date: expect.any(DateWithoutTime),
      districts: [],
      parties: [],
      precincts: [],
      seal: '',
      state: '',
      title: '',
      type: 'general',
      ballotStrings: {},
    },
    systemSettings: DEFAULT_SYSTEM_SETTINGS,
    ballotOrderInfo: {},
    ballotStyles: [],
    precincts: [],
    createdAt: expect.any(String),
    ballotsFinalizedAt: null,
    ballotLanguageConfigs: getTempBallotLanguageConfigsForCert(),
    ballotTemplateId: 'NhBallot',
  });

  expect(await apiClient.listElections({ user: vxUser })).toEqual([election]);

  const election2Definition =
    electionFamousNames2021Fixtures.readElectionDefinition();
  const electionId2 = (
    await apiClient.loadElection({
      user: vxUser,
      orgId: nonVxUser.orgId,
      electionData: election2Definition.electionData,
    })
  ).unsafeUnwrap();
  expect(electionId2).toEqual(election2Definition.election.id);

  const election2 = await apiClient.getElection({
    user: vxUser,
    electionId: electionId2,
  });

  const expectedPrecincts: Precinct[] =
    election2Definition.election.precincts.map((vxfPrecinct) => ({
      id: vxfPrecinct.id,
      name: vxfPrecinct.name,
      districtIds: [unsafeParse(DistrictIdSchema, 'district-1')],
    }));
  const expectedBallotStyles: BallotStyle[] = generateBallotStyles({
    ballotLanguageConfigs: election2.ballotLanguageConfigs,
    contests: election2Definition.election.contests,
    electionType: election2Definition.election.type,
    parties: election2Definition.election.parties,
    precincts: expectedPrecincts,
  });

  expect(election2).toEqual<ElectionRecord>({
    orgId: nonVxUser.orgId,
    election: {
      ...election2Definition.election,
      ballotStyles: expectedBallotStyles.map(convertToVxfBallotStyle),
      gridLayouts: undefined, // Grid layouts should be stripped out
    },
    systemSettings: DEFAULT_SYSTEM_SETTINGS,
    ballotOrderInfo: {},
    // TODO test that ballot styles/precincts are correct
    ballotStyles: expectedBallotStyles,
    precincts: expectedPrecincts,
    createdAt: expect.any(String),
    ballotsFinalizedAt: null,
    ballotLanguageConfigs: getTempBallotLanguageConfigsForCert(),
    ballotTemplateId: 'VxDefaultBallot',
  });

  expect(await apiClient.listElections({ user: vxUser })).toEqual([
    election,
    election2,
  ]);

  const updatedElection: Election = {
    ...election.election,
    title: 'Updated Election',
    type: 'primary',
  };

  await apiClient.updateElection({
    electionId,
    election: updatedElection,
  });

  expect(await apiClient.getElection({ user: vxUser, electionId })).toEqual({
    ...election,
    election: updatedElection,
  });

  await apiClient.deleteElection({ electionId });

  expect(await apiClient.listElections({ user: vxUser })).toEqual([election2]);
});

test('update election info', async () => {
  const { apiClient } = await setupApp();
  const electionId = unsafeParse(ElectionIdSchema, 'election-1');
  (
    await apiClient.createElection({
      user: vxUser,
      orgId: nonVxUser.orgId,
      id: electionId,
    })
  ).unsafeUnwrap();

  await apiClient.updateElectionInfo({
    electionId,
    // trim text values
    title: '   Updated Election  ',
    jurisdiction: '   New Hampshire   ',
    state: '   NH   ',
    seal: '\r\n<svg>updated seal</svg>\r\n',
    type: 'primary',
    date: new DateWithoutTime('2022-01-01'),
  });

  const record = await apiClient.getElection({ user: vxUser, electionId });
  const { election } = record;
  expect(election.title).toEqual('Updated Election');
  expect(election.type).toEqual('primary');
  expect(election.state).toEqual('NH');
  expect(election.county.name).toEqual('New Hampshire');
  expect(election.seal).toEqual('\r\n<svg>updated seal</svg>\r\n');
  expect(election.date).toEqual(new DateWithoutTime('2022-01-01'));

  // empty string values are rejected
  await suppressingConsoleOutput(() =>
    expect(
      apiClient.updateElectionInfo({
        electionId,
        type: 'primary',
        title: '',
        jurisdiction: '  ',
        state: '',
        seal: '',
        date: new DateWithoutTime('2022-01-01'),
      })
    ).rejects.toThrow()
  );
});

test.skip('Updating contests with candidate rotation', async () => {
  const { apiClient } = await setupApp();
  const electionId = (
    await apiClient.loadElection({
      user: vxUser,
      orgId: nonVxUser.orgId,
      electionData: electionFamousNames2021Fixtures.electionJson.asText(),
    })
  ).unsafeUnwrap();
  const electionRecord = await apiClient.getElection({
    user: vxUser,
    electionId,
  });
  const contest = electionRecord.election.contests.find(
    (c): c is CandidateContest =>
      c.type === 'candidate' && c.candidates.length > 2
  )!;
  expect(contest.candidates.map((c) => c.name)).toMatchInlineSnapshot(`
[
  "Winston Churchill",
  "Oprah Winfrey",
  "Louis Armstrong",
]
`);

  // Update with no changes just to trigger candidate rotation
  await apiClient.updateElection({
    electionId,
    election: electionRecord.election,
  });

  const updatedElectionRecord = await apiClient.getElection({
    user: vxUser,
    electionId,
  });
  const updatedContest = updatedElectionRecord.election.contests.find(
    (c): c is CandidateContest => c.id === contest.id
  )!;
  expect(updatedContest.candidates.map((c) => c.name)).toMatchInlineSnapshot(`
[
  "Louis Armstrong",
  "Winston Churchill",
  "Oprah Winfrey",
]
`);

  // Rotation logic is tested in candidate_rotation.test.ts
  // Here we just want to make sure that rotation occurred.
  expect(updatedContest.candidates).not.toEqual(contest.candidates);
  expect(updatedContest.candidates.length).toEqual(contest.candidates.length);
  expect(new Set(updatedContest.candidates)).toEqual(
    new Set(contest.candidates)
  );
});

test('Update system settings', async () => {
  const { apiClient } = await setupApp();
  const electionId = unsafeParse(ElectionIdSchema, 'election-1');
  (
    await apiClient.createElection({
      user: vxUser,
      orgId: nonVxUser.orgId,
      id: electionId,
    })
  ).unsafeUnwrap();
  const electionRecord = await apiClient.getElection({
    user: vxUser,
    electionId,
  });

  expect(electionRecord.systemSettings).toEqual(DEFAULT_SYSTEM_SETTINGS);

  const updatedSystemSettings: SystemSettings = {
    ...electionRecord.systemSettings,
    markThresholds: {
      definite: 0.9,
      marginal: 0.8,
    },
    precinctScanAdjudicationReasons: [AdjudicationReason.Overvote],
    centralScanAdjudicationReasons: [
      AdjudicationReason.Undervote,
      AdjudicationReason.MarginalMark,
    ],
  };
  expect(updatedSystemSettings).not.toEqual(DEFAULT_SYSTEM_SETTINGS);

  await apiClient.updateSystemSettings({
    electionId,
    systemSettings: updatedSystemSettings,
  });

  expect(await apiClient.getElection({ user: vxUser, electionId })).toEqual({
    ...electionRecord,
    systemSettings: updatedSystemSettings,
  });
});

test('Update ballot order info', async () => {
  const { apiClient } = await setupApp();
  const electionId = unsafeParse(ElectionIdSchema, 'election-1');
  (
    await apiClient.createElection({
      user: vxUser,
      orgId: nonVxUser.orgId,
      id: electionId,
    })
  ).unsafeUnwrap();

  const electionRecord = await apiClient.getElection({
    user: vxUser,
    electionId,
  });
  expect(electionRecord.ballotOrderInfo).toEqual({});

  const updateBallotOrderInfo: BallotOrderInfo = {
    absenteeBallotCount: '100',
    deliveryAddress: '123 Main St, Town, NH, 00000',
    deliveryRecipientName: 'Clerky Clerkson',
    ballotColor: 'Yellow for town, white for school',
    precinctBallotCount: '200',
    shouldAbsenteeBallotsBeScoredForFolding: true,
  };
  await apiClient.updateBallotOrderInfo({
    electionId,
    ballotOrderInfo: updateBallotOrderInfo,
  });

  expect(await apiClient.getElection({ user: vxUser, electionId })).toEqual({
    ...electionRecord,
    ballotOrderInfo: updateBallotOrderInfo,
  });
});

test('Finalize ballots', async () => {
  const { apiClient } = await setupApp();
  const electionId = (
    await apiClient.loadElection({
      user: vxUser,
      orgId: nonVxUser.orgId,
      electionData: electionFamousNames2021Fixtures.electionJson.asText(),
    })
  ).unsafeUnwrap();

  expect(await apiClient.getBallotsFinalizedAt({ electionId })).toEqual(null);

  const finalizedAt = new Date();
  await apiClient.finalizeBallots({ electionId });

  expect(
    (await apiClient.getBallotsFinalizedAt({ electionId }))!.valueOf() / 1000
  ).toBeCloseTo(finalizedAt.valueOf() / 1000);

  await apiClient.unfinalizeBallots({ electionId });

  expect(await apiClient.getBallotsFinalizedAt({ electionId })).toEqual(null);
});

test.skip('Election package management', async () => {
  const baseElectionDefinition =
    electionFamousNames2021Fixtures.readElectionDefinition();
  const { apiClient, workspace, fileStorageClient } = await setupApp();

  const electionId = (
    await apiClient.loadElection({
      user: vxUser,
      orgId: nonVxUser.orgId,
      electionData: baseElectionDefinition.electionData,
    })
  ).unsafeUnwrap();
  const election = await apiClient.getElection({ user: vxUser, electionId });

  // Without mocking all the translations some ballot styles for non-English languages don't fit on a letter
  // page for this election. To get around this we use legal paper size for the purposes of this test.
  await apiClient.updateElection({
    electionId,
    election: {
      ...election.election,
      ballotLayout: {
        ...election.election.ballotLayout,
        paperSize: HmpbBallotPaperSize.Legal,
      },
    },
  });

  const electionPackageBeforeExport = await apiClient.getElectionPackage({
    electionId,
  });
  expect(electionPackageBeforeExport).toEqual({});

  // Initiate an export
  await apiClient.exportElectionPackage({
    user: vxUser,
    electionId,
    electionSerializationFormat: 'vxf',
  });
  const expectedPayload = `{"electionId":"${electionId}","electionSerializationFormat":"vxf","orgId":${JSON.stringify(
    vxUser.orgId
  )}}`;
  const electionPackageAfterInitiatingExport =
    await apiClient.getElectionPackage({ electionId });
  expect(electionPackageAfterInitiatingExport).toEqual<ElectionPackage>({
    task: {
      createdAt: expect.any(Date),
      id: expect.any(String),
      payload: expectedPayload,
      taskName: 'generate_election_package',
    },
  });
  const taskId = assertDefined(electionPackageAfterInitiatingExport.task).id;

  // Check that initiating an export before a prior has completed doesn't trigger a new background
  // task (even with a different serialization format)
  await apiClient.exportElectionPackage({
    user: vxUser,
    electionId,
    electionSerializationFormat: 'cdf',
  });
  const electionPackageAfterInitiatingRedundantExport =
    await apiClient.getElectionPackage({ electionId });
  expect(electionPackageAfterInitiatingRedundantExport).toEqual(
    electionPackageAfterInitiatingExport
  );

  // Complete an export
  await processNextBackgroundTaskIfAny({ fileStorageClient, workspace });
  const electionPackageAfterExport = await apiClient.getElectionPackage({
    electionId,
  });
  expect(electionPackageAfterExport).toEqual<ElectionPackage>({
    task: {
      completedAt: expect.any(Date),
      createdAt: expect.any(Date),
      id: taskId,
      payload: expectedPayload,
      startedAt: expect.any(Date),
      taskName: 'generate_election_package',
    },
    url: expect.stringMatching(ELECTION_PACKAGE_FILE_NAME_REGEX),
  });

  // Check that initiating an export after a prior has completed does trigger a new background task
  await apiClient.exportElectionPackage({
    user: vxUser,
    electionId,
    electionSerializationFormat: 'vxf',
  });
  const electionPackageAfterInitiatingSecondExport =
    await apiClient.getElectionPackage({ electionId });
  expect(electionPackageAfterInitiatingSecondExport).toEqual<ElectionPackage>({
    task: {
      createdAt: expect.any(Date),
      id: expect.any(String),
      payload: expectedPayload,
      taskName: 'generate_election_package',
    },
    url: expect.stringMatching(ELECTION_PACKAGE_FILE_NAME_REGEX),
  });
  const secondTaskId = assertDefined(
    electionPackageAfterInitiatingSecondExport.task
  ).id;
  expect(secondTaskId).not.toEqual(taskId);
});

test.skip('Election package export', async () => {
  const baseElectionDefinition =
    electionFamousNames2021Fixtures.readElectionDefinition();
  // Without mocking all the translations some ballot styles for non-English languages don't fit on a letter
  // page for this election. To get around this we use legal paper size for the purposes of this test.
  const electionWithLegalPaper: Election = {
    ...baseElectionDefinition.election,
    ballotLayout: {
      ...baseElectionDefinition.election.ballotLayout,
      paperSize: HmpbBallotPaperSize.Legal,
    },
  };
  const mockSystemSettings: SystemSettings = {
    ...DEFAULT_SYSTEM_SETTINGS,
    precinctScanAdjudicationReasons: [
      AdjudicationReason.Overvote,
      AdjudicationReason.UnmarkedWriteIn,
    ],
  };
  const { apiClient, workspace, fileStorageClient } = await setupApp();

  const electionId = (
    await apiClient.loadElection({
      user: vxUser,
      orgId: nonVxUser.orgId,
      electionData: JSON.stringify(electionWithLegalPaper),
    })
  ).unsafeUnwrap();
  await apiClient.updateSystemSettings({
    electionId,
    systemSettings: mockSystemSettings,
  });
  const electionRecord = await apiClient.getElection({
    user: vxUser,
    electionId,
  });

  const { ballotLanguageConfigs, election: appElection } = electionRecord;

  const electionPackageFilePath = await exportElectionPackage({
    user: vxUser,
    fileStorageClient,
    apiClient,
    electionId,
    workspace,
    electionSerializationFormat: 'vxf',
  });

  const { electionPackage, electionPackageHash } = (
    await readElectionPackageFromFile(electionPackageFilePath)
  ).unsafeUnwrap();
  const {
    electionDefinition,
    metadata,
    systemSettings,
    uiStringAudioClips,
    uiStringAudioIds,
    uiStrings,
  } = electionPackage;
  assert(metadata !== undefined);
  assert(systemSettings !== undefined);
  assert(uiStringAudioClips !== undefined);
  assert(uiStringAudioIds !== undefined);
  assert(uiStrings !== undefined);

  const [, ballotHashFromFileName, electionPackageHashFromFileName] =
    electionPackageFilePath.match(ELECTION_PACKAGE_FILE_NAME_REGEX)!;
  expect(electionPackageHashFromFileName).toEqual(
    formatElectionPackageHash(electionPackageHash)
  );
  expect(ballotHashFromFileName).toEqual(
    formatBallotHash(electionDefinition.ballotHash)
  );

  //
  // Check metadata
  //

  expect(metadata.version).toEqual('latest');

  //
  // Check election definition
  //

  expect(electionDefinition.election).toEqual({
    ...electionWithLegalPaper,

    // Ballot styles are generated in the app, ignoring the ones in the inputted election
    // definition
    ballotStyles: appElection.ballotStyles,

    // The base election definition should have been extended with grid layouts. The correctness of
    // the grid layouts is tested by libs/ballot-interpreter tests.
    gridLayouts: expect.any(Array),

    // Translated strings for election content and HMPB content should have been
    // added to the election. so they can be included in the ballot hash.
    ballotStrings: expect.objectContaining({
      ...Object.fromEntries(
        Object.values(LanguageCode).map((code) => [code, expect.any(Object)])
      ),
      ...expectedEnglishBallotStrings(appElection),
    }),
  });

  //
  // Check system settings
  //

  expect(systemSettings).toEqual(mockSystemSettings);

  //
  // Check UI strings
  //

  const allBallotLanguages = getAllBallotLanguages(ballotLanguageConfigs);
  for (const languageCode of allBallotLanguages) {
    expect(countObjectLeaves(uiStrings[languageCode] ?? {})).toBeGreaterThan(
      // A number high enough to give us confidence that we've exported both app and election strings
      200
    );
  }

  for (const electionStringKey of Object.values(ElectionStringKey)) {
    // The current election definition doesn't include any yes-no contests or contest terms
    if (
      electionStringKey === ElectionStringKey.CONTEST_DESCRIPTION ||
      electionStringKey === ElectionStringKey.CONTEST_OPTION_LABEL ||
      electionStringKey === ElectionStringKey.CONTEST_TERM
    ) {
      continue;
    }

    expect(
      assertDefined(uiStrings[LanguageCode.ENGLISH])[electionStringKey]
    ).toBeDefined();
  }

  const stringsInEnglish: Array<{
    stringKey: string | [string, string];
    stringInEnglish: string;
  }> = [];
  forEachUiString(
    uiStrings,
    ({ languageCode, stringKey, stringInLanguage }) => {
      if (languageCode === LanguageCode.ENGLISH) {
        stringsInEnglish.push({ stringKey, stringInEnglish: stringInLanguage });
      }
    }
  );

  // Verify that strings were translated as expected
  for (const languageCode of allBallotLanguages) {
    if (languageCode === LanguageCode.ENGLISH) {
      continue;
    }

    for (const { stringKey, stringInEnglish } of stringsInEnglish) {
      const stringInLanguage = get(uiStrings, [languageCode, stringKey].flat());
      if (
        Array.isArray(stringKey) &&
        stringKey[0] === ElectionStringKey.BALLOT_STYLE_ID
      ) {
        expect(stringInLanguage).not.toBeDefined();
      } else if (
        Array.isArray(stringKey) &&
        stringKey[0] === ElectionStringKey.CANDIDATE_NAME
      ) {
        expect(stringInLanguage).not.toBeDefined();
      } else if (stringKey === ElectionStringKey.ELECTION_DATE) {
        expect(stringInLanguage).toBeDefined();
      } else if (stringKey === ElectionStringKey.BALLOT_LANGUAGE) {
        expect(stringInLanguage).toBeDefined();
      } else {
        expect(stringInLanguage).toBeDefined();
        expect(stringInLanguage).toEqual(
          mockCloudTranslatedText(stringInEnglish, languageCode)
        );
      }
    }
  }

  //
  // Check uiStringAudioIds.json
  //
  expect(countObjectLeaves(uiStringAudioIds)).toEqual(
    countObjectLeaves(uiStrings) -
      Object.keys(hmpbStringsCatalog).length *
        Object.values(LanguageCode).length
  );

  //
  // Check audioClips.jsonl
  //

  const audioIds: Set<string> = new Set(
    getObjectLeaves(uiStringAudioIds)
      .flat()
      .filter((audioId): audioId is string => {
        assert(typeof audioId === 'string');
        return !(audioId.startsWith('{{') && audioId.endsWith('}}'));
      })
  );
  const audioIdsInAudioClipsFile = new Set(
    uiStringAudioClips.map(({ id }) => id)
  );
  expect(audioIdsInAudioClipsFile.size).toEqual(audioIds.size);
  for (const audioId of audioIds) {
    expect(audioIdsInAudioClipsFile.has(audioId)).toEqual(true);
  }

  for (const { dataBase64 } of uiStringAudioClips) {
    expect(
      isMockCloudSynthesizedSpeech(
        Buffer.from(dataBase64, 'base64').toString('utf-8')
      )
    ).toEqual(true);
  }
});

// Spy on the ballot rendering function so we can check that it's called with the
// right arguments.
vi.mock(import('@votingworks/hmpb'), async (importActual) => {
  const original = await importActual();
  return {
    ...original,
    renderAllBallotsAndCreateElectionDefinition: vi.fn(
      original.renderAllBallotsAndCreateElectionDefinition
    ),
  } as unknown as typeof original;
});

test.skip('Export all ballots', async () => {
  // This test runs unnecessarily long if we're generating exports for all
  // languages, so disabling multi-language support for this case:
  mockFeatureFlagger.disableFeatureFlag(
    BooleanEnvironmentVariableName.ENABLE_CLOUD_TRANSLATION_AND_SPEECH_SYNTHESIS
  );

  const baseElectionDefinition =
    electionFamousNames2021Fixtures.readElectionDefinition();
  const { apiClient } = await setupApp();

  const electionId = (
    await apiClient.loadElection({
      user: vxUser,
      orgId: nonVxUser.orgId,
      electionData: baseElectionDefinition.electionData,
    })
  ).unsafeUnwrap();
  const { ballotStyles, election, precincts } = await apiClient.getElection({
    user: vxUser,
    electionId,
  });

  // @ts-expect-error - `exportAllBallots` was removed from the API
  const { zipContents } = await apiClient.exportAllBallots({
    electionId,
    electionSerializationFormat: 'vxf',
  });
  const zip = await JsZip.loadAsync(zipContents);

  const expectedFileNames = [
    BALLOT_STYLE_READINESS_REPORT_FILE_NAME,
    ...ballotStyles
      .flatMap(({ id, precinctsOrSplits }) =>
        precinctsOrSplits.map((p) => ({
          ballotStyleId: id,
          precinctId: p.precinctId,
        }))
      )
      .flatMap(({ ballotStyleId, precinctId }) => {
        const precinctName = find(
          precincts,
          (p) => p.id === precinctId
        ).name.replaceAll(' ', '_');

        const suffix = `ballot-${precinctName}-${ballotStyleId}.pdf`;

        return [
          `official-precinct-${suffix}`,
          `test-precinct-${suffix}`,
          `sample-precinct-${suffix}`,
          `official-absentee-${suffix}`,
          `test-absentee-${suffix}`,
          `sample-absentee-${suffix}`,
        ];
      }),
  ].sort();
  expect(Object.keys(zip.files).sort()).toEqual(expectedFileNames);

  const readinessReportFileContents =
    await zip.files[BALLOT_STYLE_READINESS_REPORT_FILE_NAME].async('text');
  expect(readinessReportFileContents).toContain(MOCK_READINESS_REPORT_CONTENTS);

  // Ballot appearance is tested by fixtures in libs/hmpb, so we
  // just make sure we got a PDF and that we called the layout function with the
  // right arguments.
  for (const file of Object.values(zip.files)) {
    expect(await file.async('text')).toContain('%PDF');
  }
  expect(renderAllBallotsAndCreateElectionDefinition).toHaveBeenCalledTimes(1);
  const ballotCombos: Array<[BallotType, BallotMode]> = [
    [BallotType.Precinct, 'official'],
    [BallotType.Precinct, 'test'],
    [BallotType.Precinct, 'sample'],
    [BallotType.Absentee, 'official'],
    [BallotType.Absentee, 'test'],
    [BallotType.Absentee, 'sample'],
  ];
  const expectedBallotProps = election.ballotStyles.flatMap((ballotStyle) =>
    ballotStyle.precincts.flatMap((precinctId) =>
      ballotCombos.map(
        ([ballotType, ballotMode]): BaseBallotProps => ({
          election: {
            ...election,
            ballotStrings: expectedEnglishBallotStrings(election),
          },
          ballotStyleId: ballotStyle.id,
          precinctId,
          ballotType,
          ballotMode,
        })
      )
    )
  );
  expect(renderAllBallotsAndCreateElectionDefinition).toHaveBeenCalledWith(
    expect.any(Object), // Renderer
    ballotTemplates.VxDefaultBallot,
    expectedBallotProps,
    'vxf'
  );
});

test('Export test decks', async () => {
  // This test runs unnecessarily long if we're generating exports for all
  // languages, so disabling multi-language support for this case:
  mockFeatureFlagger.disableFeatureFlag(
    BooleanEnvironmentVariableName.ENABLE_CLOUD_TRANSLATION_AND_SPEECH_SYNTHESIS
  );

  const electionDefinition = readElectionTwoPartyPrimaryDefinition();
  const { apiClient } = await setupApp();

  const electionId = (
    await apiClient.loadElection({
      user: vxUser,
      orgId: nonVxUser.orgId,
      electionData: electionDefinition.electionData,
    })
  ).unsafeUnwrap();
  const { election } = await apiClient.getElection({
    user: vxUser,
    electionId,
  });

  const { zipContents } = await apiClient.exportTestDecks({
    electionId,
    electionSerializationFormat: 'vxf',
  });
  const zip = await JsZip.loadAsync(zipContents);

  const precinctsWithBallots = election.precincts.filter(
    (precinct) =>
      getBallotStylesByPrecinctId(electionDefinition, precinct.id).length > 0
  );
  expect(Object.keys(zip.files).sort()).toEqual(
    [
      ...precinctsWithBallots.map(
        (precinct) => `${precinct.name.replaceAll(' ', '_')}-test-ballots.pdf`
      ),
      FULL_TEST_DECK_TALLY_REPORT_FILE_NAME,
    ].sort()
  );

  // We test the actual test deck content in test_decks.ts
  for (const file of Object.values(zip.files)) {
    expect(await file.async('text')).toContain('%PDF');
  }
  expect(renderAllBallotsAndCreateElectionDefinition).toHaveBeenCalledTimes(1);
  const expectedBallotProps = election.ballotStyles.flatMap((ballotStyle) =>
    ballotStyle.precincts.map((precinctId) => ({
      election: {
        ...election,
        ballotStrings: expectedEnglishBallotStrings(election),
      },
      ballotStyleId: ballotStyle.id,
      precinctId,
      ballotType: BallotType.Precinct,
      ballotMode: 'test',
    }))
  );
  expect(renderAllBallotsAndCreateElectionDefinition).toHaveBeenCalledWith(
    expect.any(Object), // Renderer
    ballotTemplates.VxDefaultBallot,
    expectedBallotProps,
    'vxf'
  );
});

test.skip('Consistency of ballot hash across exports', async () => {
  // This test runs unnecessarily long if we're generating exports for all
  // languages, so disabling multi-language support for this case:
  mockFeatureFlagger.disableFeatureFlag(
    BooleanEnvironmentVariableName.ENABLE_CLOUD_TRANSLATION_AND_SPEECH_SYNTHESIS
  );

  const baseElectionDefinition =
    electionFamousNames2021Fixtures.readElectionDefinition();
  const { apiClient, workspace, fileStorageClient } = await setupApp();

  const electionId = (
    await apiClient.loadElection({
      user: vxUser,
      orgId: nonVxUser.orgId,
      electionData: baseElectionDefinition.electionData,
    })
  ).unsafeUnwrap();

  // @ts-expect-error - `exportAllBallots` was removed from the API
  const allBallotsOutput = await apiClient.exportAllBallots({
    electionId,
    electionSerializationFormat: 'vxf',
  });

  const testDecksOutput = await apiClient.exportTestDecks({
    electionId,
    electionSerializationFormat: 'vxf',
  });

  const electionPackageFilePath = await exportElectionPackage({
    user: vxUser,
    fileStorageClient,
    apiClient,
    electionId,
    workspace,
    electionSerializationFormat: 'vxf',
  });
  const { electionDefinition } = (
    await readElectionPackageFromFile(electionPackageFilePath)
  ).unsafeUnwrap().electionPackage;

  expect([
    ...new Set([
      allBallotsOutput.ballotHash,
      testDecksOutput.ballotHash,
      electionDefinition.ballotHash,
    ]),
  ]).toHaveLength(1);
});

test.skip('CDF exports', async () => {
  // This test runs unnecessarily long if we're generating exports for all
  // languages, so disabling multi-language support for this case:
  mockFeatureFlagger.disableFeatureFlag(
    BooleanEnvironmentVariableName.ENABLE_CLOUD_TRANSLATION_AND_SPEECH_SYNTHESIS
  );

  const baseElectionDefinition =
    electionFamousNames2021Fixtures.readElectionDefinition();
  const { apiClient, workspace, fileStorageClient } = await setupApp();

  const electionId = (
    await apiClient.loadElection({
      user: vxUser,
      orgId: nonVxUser.orgId,
      electionData: baseElectionDefinition.electionData,
    })
  ).unsafeUnwrap();

  // @ts-expect-error - `exportAllBallots` was removed from the API
  const allBallotsOutput = await apiClient.exportAllBallots({
    electionId,
    electionSerializationFormat: 'cdf',
  });

  const testDecksOutput = await apiClient.exportTestDecks({
    electionId,
    electionSerializationFormat: 'cdf',
  });

  const electionPackageFilePath = await exportElectionPackage({
    user: vxUser,
    fileStorageClient,
    apiClient,
    electionId,
    workspace,
    electionSerializationFormat: 'cdf',
  });
  const { electionDefinition } = (
    await readElectionPackageFromFile(electionPackageFilePath)
  ).unsafeUnwrap().electionPackage;
  expect(electionDefinition.electionData).toMatch(
    /"@type": "BallotDefinition.BallotDefinition"/
  );

  expect([
    ...new Set([
      allBallotsOutput.ballotHash,
      testDecksOutput.ballotHash,
      electionDefinition.ballotHash,
    ]),
  ]).toHaveLength(1);
});

test('getBallotPreviewPdf returns a ballot pdf for precinct with splits', async () => {
  const baseElectionDefinition =
    electionPrimaryPrecinctSplitsFixtures.readElectionDefinition();
  const { apiClient } = await setupApp();

  const electionId = (
    await apiClient.loadElection({
      user: vxUser,
      orgId: nonVxUser.orgId,
      electionData: baseElectionDefinition.electionData,
    })
  ).unsafeUnwrap();
  const { ballotStyles, precincts } = await apiClient.getElection({
    user: vxUser,
    electionId,
  });

  const precinct = assertDefined(precincts.find((p) => hasSplits(p)));
  const split = precinct.splits[0];
  const ballotStyle = assertDefined(
    ballotStyles.find((style) => {
      const matchingSplit = style.precinctsOrSplits.find(
        (p) => p.precinctId === precinct.id && p.splitId === split.id
      );
      return !!matchingSplit && style.languages.includes(LanguageCode.ENGLISH);
    })
  );

  const result = (
    await apiClient.getBallotPreviewPdf({
      electionId,
      precinctId: precinct.id,
      ballotStyleId: ballotStyle.id,
      ballotType: BallotType.Precinct,
      ballotMode: 'test',
    })
  ).unsafeUnwrap();

  await expect(result.pdfData).toMatchPdfSnapshot();
});

test('getBallotPreviewPdf returns a ballot pdf for NH election with split precincts and additional config options', async () => {
  const baseElectionDefinition =
    electionPrimaryPrecinctSplitsFixtures.readElectionDefinition();
  const election: Election = {
    ...baseElectionDefinition.election,
    state: 'New Hampshire',
  };
  const { apiClient } = await setupApp();

  const electionId = (
    await apiClient.loadElection({
      user: vxUser,
      orgId: nonVxUser.orgId,
      electionData: JSON.stringify(election),
    })
  ).unsafeUnwrap();
  const { ballotStyles, precincts } = await apiClient.getElection({
    user: vxUser,
    electionId,
  });

  const splitPrecinctIndex = precincts.findIndex((p) => hasSplits(p));
  assert(splitPrecinctIndex >= 0);
  const precinct = precincts[splitPrecinctIndex] as PrecinctWithSplits;
  const split = precinct.splits[0];
  split.clerkSignatureCaption = 'Test Clerk Caption';
  split.clerkSignatureImage = readFileSync(
    './test/mockSignature.svg'
  ).toString();
  split.electionTitleOverride = 'Test Election Title Override';

  await apiClient.updatePrecincts({ electionId, precincts });

  const ballotStyle = assertDefined(
    ballotStyles.find((style) => {
      const matchingSplit = style.precinctsOrSplits.find(
        (p) => p.precinctId === precinct.id && p.splitId === split.id
      );
      return !!matchingSplit && style.languages.includes(LanguageCode.ENGLISH);
    })
  );

  const result = (
    await apiClient.getBallotPreviewPdf({
      electionId,
      precinctId: precinct.id,
      ballotStyleId: ballotStyle.id,
      ballotType: BallotType.Precinct,
      ballotMode: 'test',
    })
  ).unsafeUnwrap();

  await expect(result.pdfData).toMatchPdfSnapshot({ failureThreshold: 0.001 });
});

test('getBallotPreviewPdf returns a ballot pdf for precinct with no split', async () => {
  const baseElectionDefinition =
    electionFamousNames2021Fixtures.readElectionDefinition();
  const { apiClient } = await setupApp();

  const electionId = (
    await apiClient.loadElection({
      user: vxUser,
      orgId: nonVxUser.orgId,
      electionData: baseElectionDefinition.electionData,
    })
  ).unsafeUnwrap();
  const { ballotStyles, precincts } = await apiClient.getElection({
    user: vxUser,
    electionId,
  });

  function hasDistrictIds(
    precinct: Precinct
  ): precinct is PrecinctWithoutSplits {
    return 'districtIds' in precinct && precinct.districtIds.length > 0;
  }

  const precinct = assertDefined(precincts.find((p) => hasDistrictIds(p)));

  const result = (
    await apiClient.getBallotPreviewPdf({
      electionId,
      precinctId: precinct.id,
      ballotStyleId: assertDefined(
        ballotStyles.find(
          (style) =>
            style.districtIds.includes(precinct.districtIds[0]) &&
            style.languages.includes(LanguageCode.ENGLISH)
        )
      ).id,
      ballotType: BallotType.Precinct,
      ballotMode: 'test',
    })
  ).unsafeUnwrap();

  await expect(result.pdfData).toMatchPdfSnapshot({ failureThreshold: 0.01 });
});

function mockBallotDocument(): RenderDocument {
  return {
    getContent: vi.fn(),
    inspectElements: vi.fn(),
    renderToPdf: vi.fn().mockResolvedValue(Buffer.from('')),
    setContent: vi.fn(),
  };
}

test.skip('setBallotTemplate changes the ballot template used to render ballots', async () => {
  // This test runs unnecessarily long if we're generating exports for all
  // languages, so disabling multi-language support for this case:
  mockFeatureFlagger.disableFeatureFlag(
    BooleanEnvironmentVariableName.ENABLE_CLOUD_TRANSLATION_AND_SPEECH_SYNTHESIS
  );

  const electionDefinition =
    electionFamousNames2021Fixtures.readElectionDefinition();
  const { apiClient } = await setupApp();
  const electionId = (
    await apiClient.loadElection({
      user: vxUser,
      orgId: nonVxUser.orgId,
      electionData: electionDefinition.electionData,
    })
  ).unsafeUnwrap();
  const electionRecord = await apiClient.getElection({
    user: vxUser,
    electionId,
  });
  expect(electionRecord.ballotTemplateId).toEqual('VxDefaultBallot');

  await apiClient.setBallotTemplate({
    electionId,
    ballotTemplateId: 'NhBallot',
  });

  expect(await apiClient.getElection({ user: vxUser, electionId })).toEqual({
    ...electionRecord,
    ballotTemplateId: 'NhBallot',
  });

  const props = allBaseBallotProps(electionDefinition.election);
  vi.mocked(renderAllBallotsAndCreateElectionDefinition).mockResolvedValue({
    ballotDocuments: props.map(mockBallotDocument),
    electionDefinition,
  });
  // @ts-expect-error - `exportAllBallots` was removed from the API
  await apiClient.exportAllBallots({
    electionId,
    electionSerializationFormat: 'vxf',
  });
  expect(renderAllBallotsAndCreateElectionDefinition).toHaveBeenCalledWith(
    expect.any(Object), // Renderer
    ballotTemplates.NhBallot,
    expect.any(Array), // Ballot props
    'vxf'
  );
  expect(
    vi.mocked(renderAllBallotsAndCreateElectionDefinition).mock.calls[0][2]
  ).toHaveLength(props.length);
});

test.skip('v3-compatible election package', async () => {
  // This test runs unnecessarily long if we're generating exports for all
  // languages, so disabling multi-language support for this case:
  mockFeatureFlagger.disableFeatureFlag(
    BooleanEnvironmentVariableName.ENABLE_CLOUD_TRANSLATION_AND_SPEECH_SYNTHESIS
  );

  const fixtureElectionDefinition =
    electionFamousNames2021Fixtures.readElectionDefinition();
  const fixtureElection = fixtureElectionDefinition.election;
  const { apiClient, workspace, fileStorageClient } = await setupApp();
  const electionId = (
    await apiClient.loadElection({
      user: vxUser,
      orgId: nonVxUser.orgId,
      electionData: fixtureElectionDefinition.electionData,
    })
  ).unsafeUnwrap();
  await apiClient.setBallotTemplate({
    electionId,
    ballotTemplateId: 'NhBallotV3',
  });

  const electionPackageFilePath = await exportElectionPackage({
    user: vxUser,
    fileStorageClient,
    apiClient,
    electionId,
    workspace,
    electionSerializationFormat: 'vxf',
  });
  const zipFile = await openZip(readFileSync(electionPackageFilePath));
  const entries = getEntries(zipFile);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const election: any = await readJsonEntry(
    getFileByName(entries, ElectionPackageFileName.ELECTION)
  );
  // Date should be off-by-one to account for timezone bug in v3
  expect(fixtureElection.date.toISOString()).toEqual('2021-06-06');
  expect(election.date).toEqual('2021-06-07');

  // System settings should have field names matching v3 format
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const systemSettings: any = await readJsonEntry(
    getFileByName(entries, ElectionPackageFileName.SYSTEM_SETTINGS)
  );
  expect(Object.keys(systemSettings)).toEqual([
    'auth',
    'markThresholds',
    'centralScanAdjudicationReasons',
    'precinctScanAdjudicationReasons',
    'precinctScanDisallowCastingOvervotes',
  ]);

  // No other files included
  expect(entries.length).toEqual(2);
});
