/* auto-generated by NAPI-RS */
/* eslint-disable */
import type {
  BridgeInterpretResult,
  TimingMarks,
} from './src/bubble-ballot-ts/types';
import type { Election } from '@votingworks/types';

export interface BridgeInterpretOptions {
  frontNormalizedImageOutputPath?: string;
  backNormalizedImageOutputPath?: string;
  debugBasePathSideA?: string;
  debugBasePathSideB?: string;
  minimumDetectedScale?: number;
  scoreWriteIns?: boolean;
  disableVerticalStreakDetection?: boolean;
  maxCumulativeStreakWidth: number;
  retryStreakWidthThreshold: number;
}
