/* auto-generated by NAPI-RS */
/* eslint-disable */
import type {
  BridgeDecodeBmdResult,
  BridgeDecodeBubbleBallotMetadataResult,
  BridgeInterpretResult,
  TimingMarks,
} from './src/bubble-ballot-ts/types';
import type { Election } from '@votingworks/types';

export interface BridgeInterpretOptions {
  /**
   * Expected ballot hash as a hex string. The Rust interpreter slices it to
   * the partial-hash length and rejects ballots whose QR-decoded hash differs.
   */
  expectedBallotHash: string;
  frontNormalizedImageOutputPath?: string;
  backNormalizedImageOutputPath?: string;
  debugBasePathSideA?: string;
  debugBasePathSideB?: string;
  minimumDetectedScale?: number;
  scoreWriteIns?: boolean;
  disableVerticalStreakDetection?: boolean;
  maxCumulativeStreakWidth: number;
  retryStreakWidthThreshold: number;
}
