/* auto-generated by NAPI-RS */
/* eslint-disable */
import type {
  BridgeDecodeBmdResult,
  BridgeInterpretResult,
  TimingMarks,
} from './src/bubble-ballot-ts/types';
import type { Election } from '@votingworks/types';

export interface BridgeInterpretOptions {
  frontNormalizedImageOutputPath?: string;
  backNormalizedImageOutputPath?: string;
  debugBasePathSideA?: string;
  debugBasePathSideB?: string;
  minimumDetectedScale?: number;
  scoreWriteIns?: boolean;
  disableVerticalStreakDetection?: boolean;
  maxCumulativeStreakWidth: number;
  retryStreakWidthThreshold: number;
}
/**
 * Decodes raw QR code bytes as either a single-page `CastVoteRecord` (VX\x02)
 * or a multi-page `MultiPageCastVoteRecord` (VB\x01). Used for cross-language
 * testing to verify the Rust decoder matches the TypeScript encoder.
 */
export declare function decodeBmdBallotData(election: Election, data: Buffer): Promise<BridgeDecodeBmdResult>

/**
 * Encodes a `CastVoteRecord` or `MultiPageCastVoteRecord` to raw bytes
 * using the Rust bitstream encoder. Used for cross-language testing to
 * verify the Rust encoder matches the TypeScript decoder.
 */
export declare function encodeBmdBallotData(election: Election, record: BridgeDecodeBmdResult): Promise<Buffer>

export declare function findTimingMarkGridFromImage(imageWidth: number, imageHeight: number, imageData: Buffer | Uint8ClampedArray, debugPath?: string): Promise<TimingMarks>

export declare function findTimingMarkGridFromPath(imagePath: string, debugPath?: string): Promise<TimingMarks>

export declare function interpretImages(election: Election, sideAImageWidth: number, sideAImageHeight: number, sideAImageData: Buffer | Uint8ClampedArray, sideBImageWidth: number, sideBImageHeight: number, sideBImageData: Buffer | Uint8ClampedArray, options: BridgeInterpretOptions): Promise<BridgeInterpretResult>

export declare function interpretPaths(election: Election, sideAImagePath: string, sideBImagePath: string, options: BridgeInterpretOptions): Promise<BridgeInterpretResult>

export declare function runBlankPaperDiagnosticFromPath(imagePath: string, debugPath?: string): Promise<boolean>

/** Encodes image data (RGBA or grayscale) as a grayscale PNG and writes it to disk. */
export declare function writeImageToPng(path: string, width: number, height: number, data: Buffer | Uint8ClampedArray): Promise<void>
