/* auto-generated by NAPI-RS */
/* eslint-disable */
import type {
  BridgeInterpretResult,
  TimingMarks,
} from './src/bubble-ballot-ts/types';
import type { Election } from '@votingworks/types';

export interface BridgeInterpretOptions {
  frontNormalizedImageOutputPath?: string;
  backNormalizedImageOutputPath?: string;
  debugBasePathSideA?: string;
  debugBasePathSideB?: string;
  minimumDetectedScale?: number;
  scoreWriteIns?: boolean;
  disableVerticalStreakDetection?: boolean;
  maxCumulativeStreakWidth: number;
  retryStreakWidthThreshold: number;
}
export declare function findTimingMarkGridFromImage(imageWidth: number, imageHeight: number, imageData: Buffer | Uint8ClampedArray, debugPath?: string): Promise<TimingMarks>

export declare function findTimingMarkGridFromPath(imagePath: string, debugPath?: string): Promise<TimingMarks>

export declare function interpretImages(election: Election, sideAImageWidth: number, sideAImageHeight: number, sideAImageData: Buffer | Uint8ClampedArray, sideBImageWidth: number, sideBImageHeight: number, sideBImageData: Buffer | Uint8ClampedArray, options: BridgeInterpretOptions): Promise<BridgeInterpretResult>

export declare function interpretPaths(election: Election, sideAImagePath: string, sideBImagePath: string, options: BridgeInterpretOptions): Promise<BridgeInterpretResult>

export declare function runBlankPaperDiagnosticFromPath(imagePath: string, debugPath?: string): Promise<boolean>
