/* auto-generated by NAPI-RS */
/* eslint-disable */
import type {
  BridgeDecodeBmdResult,
  BridgeDecodeBubbleBallotMetadataResult,
  BridgeInterpretResult,
  TimingMarks,
} from './src/bubble-ballot-ts/types';
import type { Election } from '@votingworks/types';

export interface BridgeInterpretOptions {
  /**
   * Expected ballot hash as a hex string. The Rust interpreter slices it to
   * the partial-hash length and rejects ballots whose QR-decoded hash differs.
   */
  expectedBallotHash: string;
  frontNormalizedImageOutputPath?: string;
  backNormalizedImageOutputPath?: string;
  debugBasePathSideA?: string;
  debugBasePathSideB?: string;
  minimumDetectedScale?: number;
  scoreWriteIns?: boolean;
  disableVerticalStreakDetection?: boolean;
  maxCumulativeStreakWidth: number;
  retryStreakWidthThreshold: number;
}
/**
 * Decodes raw QR code bytes as a `CastVoteRecord` (VS\x01). Used for
 * cross-language testing to verify the Rust decoder matches the TypeScript
 * encoder.
 */
export declare function decodeBmdBallotData(election: Election, data: Buffer): Promise<BridgeDecodeBmdResult>

/**
 * Decodes raw QR code bytes as bubble ballot page metadata (VB\x01). Used for
 * cross-language testing to verify the Rust decoder matches the TypeScript
 * encoder.
 */
export declare function decodeBubbleBallotMetadata(election: Election, data: Buffer, expectedBallotHash: string): Promise<BridgeDecodeBubbleBallotMetadataResult>

/**
 * Encodes a `CastVoteRecord` to raw bytes using the Rust bitstream
 * encoder. Used for cross-language testing to verify the Rust encoder
 * matches the TypeScript decoder.
 */
export declare function encodeBmdBallotData(election: Election, record: BridgeDecodeBmdResult): Promise<Buffer>

/**
 * Encodes bubble ballot page metadata to raw bytes using the Rust bitstream
 * encoder. Used for cross-language testing to verify the Rust encoder matches
 * the TypeScript encoder byte for byte.
 */
export declare function encodeBubbleBallotMetadata(election: Election, metadata: BridgeDecodeBubbleBallotMetadataResult, version: 'v4.0' | 'v4.1'): Promise<Buffer>

export declare function findTimingMarkGridFromImage(imageWidth: number, imageHeight: number, imageData: Buffer | Uint8ClampedArray, debugPath?: string): Promise<TimingMarks>

export declare function findTimingMarkGridFromPath(imagePath: string, debugPath?: string): Promise<TimingMarks>

export declare function interpretImages(election: Election, sideAImageWidth: number, sideAImageHeight: number, sideAImageData: Buffer | Uint8ClampedArray, sideBImageWidth: number, sideBImageHeight: number, sideBImageData: Buffer | Uint8ClampedArray, options: BridgeInterpretOptions): Promise<BridgeInterpretResult>

export declare function interpretPaths(election: Election, sideAImagePath: string, sideBImagePath: string, options: BridgeInterpretOptions): Promise<BridgeInterpretResult>

export declare function runBlankPaperDiagnosticFromImage(imageWidth: number, imageHeight: number, imageData: Buffer | Uint8ClampedArray, debugPath?: string): Promise<boolean>

export declare function runBlankPaperDiagnosticFromPath(imagePath: string, debugPath?: string): Promise<boolean>

/** Encodes image data (RGBA or grayscale) as a grayscale PNG and writes it to disk. */
export declare function writeImageToPng(path: string, width: number, height: number, data: Buffer | Uint8ClampedArray): Promise<void>
