import fs from 'node:fs';
import { basename } from 'node:path';
import tmp from 'tmp';
import { convert } from './convert.js';

test('creating a resource for a directory', async () => {
  fs.mkdirSync('/tmp/data/electionFixture/cvr-files', { recursive: true });
  const tmpDirName = tmp.dirSync({
    template: '/tmp/data/electionFixture/cvr-files/resource-XXXXXX',
  }).name;
  const result = await convert({
    path: tmpDirName,
    tsPath: '/tmp/src/data/electionFixture/cvr-files/resource.ts',
    mimeType: 'application/octet-stream',
  });
  const tmpDirBaseName = basename(tmpDirName);
  expect(result).toContain(tmpDirBaseName);
  expect(result.replace(tmpDirBaseName, 'resource')).toMatchInlineSnapshot(`
    "/* Generated by res-to-ts. DO NOT EDIT */
    /* eslint-disable */
    /* istanbul ignore file */

    import * as fs from 'node:fs';
    import { tmpdir } from 'node:os';
    import { resolve, sep } from 'node:path';

    const copiedDirectories: string[] = [];

    if (typeof jest !== 'undefined') {
      afterAll(() => {
        for (const copiedDirectory of copiedDirectories) {
          fs.rmSync(copiedDirectory, { recursive: true, force: true });
        }
      });
    }

    export function asDirectoryPath(): string {
      const tmpDir = fs.mkdtempSync(tmpdir() + sep);
      const resolved = resolve(
        __dirname,
        '../../../../data/electionFixture/cvr-files/resource'
      );
      fs.cpSync(resolved, tmpDir, { recursive: true });
      copiedDirectories.push(tmpDir);
      return tmpDir;
    }

    "
  `);
});
