import { promises as fs } from 'fs';
import { relative } from 'path';
import { isImageMimeType, isTextMimeType } from './mime';

/**
 * A resource to be converted.
 */
export interface Resource {
  readonly path: string;
  readonly tsPath: string;
  readonly mimeType: string;
}

/**
 * Converts a resource to be readable as a TypeScript file.
 */
export async function convert({ path, mimeType }: Resource): Promise<string> {
  const relativePath = relative(process.cwd(), path);
  const isImageResource = isImageMimeType(mimeType);
  const isTextResource = isTextMimeType(mimeType);
  const resourceData = await fs.readFile(path);
  const lines: string[] = [
    `/* Generated by res-to-ts. DO NOT EDIT */`,
    `/* eslint-disable */`,
    `/* istanbul ignore file */`,
  ];

  if (isImageResource) {
    lines.push(
      `import { createCanvas, Image, ImageData, loadImage } from 'canvas';`,
      ``
    );
  }

  lines.push(
    `/**`,
    ` * Data of ${relativePath} encoded as base64.`,
    ` */`,
    `const resourceDataBase64 = '${resourceData.toString('base64')}';`,
    ``,
    `/**`,
    ` * MIME type of ${relativePath}.`,
    ` */`,
    `export const mimeType = '${mimeType}';`,
    ``,
    `/**`,
    ` * Convert to a \`data:\` URL of ${relativePath}, suitable for embedding in HTML.`,
    ` */`,
    `export function asDataUrl() {`,
    `  return \`data:\${mimeType};base64,\${resourceDataBase64}\`;`,
    `}`,
    ``,
    `/**`,
    ` * Raw data of ${relativePath}.`,
    ` */`,
    `export function asBuffer(): Buffer {`,
    `  return Buffer.from(resourceDataBase64, 'base64');`,
    `}`
  );

  if (isTextResource) {
    lines.push(
      ``,
      `/**`,
      ` * Text content of ${relativePath}.`,
      ` */`,
      `export function asText(): string {`,
      `  return asBuffer().toString('utf-8');`,
      `}`
    );
  }

  if (isImageResource) {
    lines.push(
      ``,
      `/**`,
      ` * Converts ${relativePath} to an \`Image\`.`,
      ` */`,
      `export async function asImage(): Promise<Image> {`,
      // Use `loadImage` with a data URL because `Buffer` only works in NodeJS.
      `  return await loadImage(asDataUrl());`,
      `}`,
      ``,
      `/**`,
      ` * Converts ${relativePath} to an \`ImageData\`.`,
      ` */`,
      `export async function asImageData(): Promise<ImageData> {`,
      `  const image = await asImage();`,
      `  const canvas = createCanvas(image.width, image.height);`,
      `  const context = canvas.getContext('2d');`,
      `  context.drawImage(image, 0, 0);`,
      `  return context.getImageData(0, 0, image.width, image.height);`,
      `}`
    );
  }

  return lines.join('\n');
}
