#!/bin/bash

pnpm build:app-strings-catalog

echo
echo 'Checking for uncommitted app string catalog updates...'

if [[ `git status ./src/ui_strings/app_strings_catalog --porcelain` ]]; then
  echo
  echo -e '\033[0;31m ❌ App strings catalog is out of date. Run `pnpm build:app-strings-catalog` to fix.'
  echo
  exit 1
else
  exit 0
fi
