#!/usr/bin/env node

require('esbuild-runner').install({
  type: 'transform',
});
require('./demo.ts')
  .main(process.argv.slice(2))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
