#!/usr/bin/env bash

set -euo pipefail

VERITY_HASH="$(cat /proc/cmdline | awk -F'verity.hash=' '{print $2}' | cut -d' ' -f1)"

if [[ ! -z "${VERITY_HASH}" ]]; then
    echo "${VERITY_HASH}"
else
    echo "UNVERIFIED"
fi
