/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Convert a VX-formatted log file to a CDF-formatted log file and calls the
 * provided callback after completion.
 *
 * # Errors
 *
 * Throws if the source is not a known source.
 */
export declare function convertVxLogToCdf(
log: (
eventId: import('@votingworks/logging').LogEventId,
message: string,
disposition: import('@votingworks/logging').LogDisposition
) => void,
source: import('@votingworks/logging').LogSource,
machineId: string,
codeVersion: string,
inputPath: string,
outputPath: string,
compressed: boolean,
callback: (error: Error | null) => void,
): void
