/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Convert a VX-formatted log file to a CDF-formatted log file. */
export declare function convertVxLogToCdf(
logger: import('@votingworks/logging').Logger,
machineId: string,
codeVersion: string,
inputPath: string,
outputPath: string
): void
