use std::fmt;

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum AamvaIssuingJurisdiction {
    // US States
    VA,
    NY,
    MA,
    MD,
    NC,
    SC,
    CT,
    LA,
    MT,
    NM,
    FL,
    DE,
    CA,
    TX,
    IA,
    CO,
    AR,
    OH,
    VT,
    PA,
    AZ,
    OR,
    MO,
    WI,
    MI,
    AL,
    ND,
    IL,
    NJ,
    IN,
    MN,
    NH,
    UT,
    ME,
    SD,
    DC,
    WA,
    KY,
    HI,
    NV,
    ID,
    MS,
    RI,
    TN,
    NE,
    GA,
    OK,
    AK,
    WY,
    WV,
    VI,

    AS, // American Samoa
    MP, // Northern Marianna Islands
    PR, // Puerto Rico
    GU, // Guam
    StateDept,
    None,
}

impl AamvaIssuingJurisdiction {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::VA => "VA",
            Self::NY => "NY",
            Self::MA => "MA",
            Self::MD => "MD",
            Self::NC => "NC",
            Self::SC => "SC",
            Self::CT => "CT",
            Self::LA => "LA",
            Self::MT => "MT",
            Self::NM => "NM",
            Self::FL => "FL",
            Self::DE => "DE",
            Self::CA => "CA",
            Self::TX => "TX",
            Self::IA => "IA",
            Self::CO => "CO",
            Self::AR => "AR",
            Self::OH => "OH",
            Self::VT => "VT",
            Self::PA => "PA",
            Self::AZ => "AZ",
            Self::OR => "OR",
            Self::MO => "MO",
            Self::WI => "WI",
            Self::MI => "MI",
            Self::AL => "AL",
            Self::ND => "ND",
            Self::IL => "IL",
            Self::NJ => "NJ",
            Self::IN => "IN",
            Self::MN => "MN",
            Self::NH => "NH",
            Self::UT => "UT",
            Self::ME => "ME",
            Self::SD => "SD",
            Self::DC => "DC",
            Self::WA => "WA",
            Self::KY => "KY",
            Self::HI => "HI",
            Self::NV => "NV",
            Self::ID => "ID",
            Self::MS => "MS",
            Self::RI => "RI",
            Self::TN => "TN",
            Self::NE => "NE",
            Self::GA => "GA",
            Self::OK => "OK",
            Self::AK => "AK",
            Self::WY => "WY",
            Self::WV => "WV",
            Self::VI => "VI",
            Self::AS => "AS",
            Self::MP => "MP",
            Self::PR => "PR",
            Self::GU => "GU",
            Self::StateDept => "StateDept",
            Self::None => "None",
        }
    }
}

impl fmt::Display for AamvaIssuingJurisdiction {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Lookup a six-digit IIN string and return its jurisdiction enum.
pub fn iin_to_issuing_jurisdiction(iin: &str) -> AamvaIssuingJurisdiction {
    match iin {
        // States
        "636000" => AamvaIssuingJurisdiction::VA,
        "636001" => AamvaIssuingJurisdiction::NY,
        "636002" => AamvaIssuingJurisdiction::MA,
        "636003" => AamvaIssuingJurisdiction::MD,
        "636004" => AamvaIssuingJurisdiction::NC,
        "636005" => AamvaIssuingJurisdiction::SC,
        "636006" => AamvaIssuingJurisdiction::CT,
        "636007" => AamvaIssuingJurisdiction::LA,
        "636008" => AamvaIssuingJurisdiction::MT,
        "636009" => AamvaIssuingJurisdiction::NM,
        "636010" => AamvaIssuingJurisdiction::FL,
        "636011" => AamvaIssuingJurisdiction::DE,
        "636014" => AamvaIssuingJurisdiction::CA,
        "636015" => AamvaIssuingJurisdiction::TX,
        "636018" => AamvaIssuingJurisdiction::IA,
        "636019" => AamvaIssuingJurisdiction::GU,
        "636020" => AamvaIssuingJurisdiction::CO,
        "636021" => AamvaIssuingJurisdiction::AR,
        "636023" => AamvaIssuingJurisdiction::OH,
        "636024" => AamvaIssuingJurisdiction::VT,
        "636025" => AamvaIssuingJurisdiction::PA,
        "636026" => AamvaIssuingJurisdiction::AZ,
        "636029" => AamvaIssuingJurisdiction::OR,
        "636030" => AamvaIssuingJurisdiction::MO,
        "636031" => AamvaIssuingJurisdiction::WI,
        "636032" => AamvaIssuingJurisdiction::MI,
        "636033" => AamvaIssuingJurisdiction::AL,
        "636034" => AamvaIssuingJurisdiction::ND,
        "636035" => AamvaIssuingJurisdiction::IL,
        "636036" => AamvaIssuingJurisdiction::NJ,
        "636037" => AamvaIssuingJurisdiction::IN,
        "636038" => AamvaIssuingJurisdiction::MN,
        "636039" => AamvaIssuingJurisdiction::NH,
        "636040" => AamvaIssuingJurisdiction::UT,
        "636041" => AamvaIssuingJurisdiction::ME,
        "636042" => AamvaIssuingJurisdiction::SD,
        "636043" => AamvaIssuingJurisdiction::DC,
        "636045" => AamvaIssuingJurisdiction::WA,
        "636046" => AamvaIssuingJurisdiction::KY,
        "636047" => AamvaIssuingJurisdiction::HI,
        "636049" => AamvaIssuingJurisdiction::NV,
        "636050" => AamvaIssuingJurisdiction::ID,
        "636051" => AamvaIssuingJurisdiction::MS,
        "636052" => AamvaIssuingJurisdiction::RI,
        "636053" => AamvaIssuingJurisdiction::TN,
        "636054" => AamvaIssuingJurisdiction::NE,
        "636055" => AamvaIssuingJurisdiction::GA,
        "636058" => AamvaIssuingJurisdiction::OK,
        "636059" => AamvaIssuingJurisdiction::AK,
        "636060" => AamvaIssuingJurisdiction::WY,
        "636061" => AamvaIssuingJurisdiction::WV,
        "636062" => AamvaIssuingJurisdiction::VI,

        // U.S. territories
        "604427" => AamvaIssuingJurisdiction::AS,
        "604430" => AamvaIssuingJurisdiction::MP,
        "604431" => AamvaIssuingJurisdiction::PR,

        "636027" => AamvaIssuingJurisdiction::StateDept,

        _ => AamvaIssuingJurisdiction::None,
    }
}
