[package]
name = "controllerd"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "controllerd"
path = "src/controllerd.rs"

[dependencies]
crc16 = { workspace = true }
num_enum = { workspace = true }
serialport = { workspace = true }
thiserror = { workspace = true }
uinput = { workspace = true }
