/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Pre-compiled CSS rules and loaded fonts. Create once per stylesheet set
 * and reuse across many `query`/`render_to_pdf` calls to avoid redundant
 * CSS parsing, base64 font decoding, and TTF loading.
 */
export declare class RenderContext {
  /**
   * Create a new context by parsing CSS and loading fonts from the given
   * HTML (typically just `<style>` tags).
   */
  constructor(stylesHtml: string);
  /**
   * Query elements matching a CSS selector in the given HTML document.
   * Uses the pre-compiled styles and loaded fonts from this context.
   * Any additional `<style>` tags in the document (e.g. from
   * styled-components) are merged with the pre-compiled rules.
   * Caches the layout so repeated queries on the same HTML skip
   * parsing, style resolution, and layout computation.
   */
  query(html: string, selector: string): Array<ElementInfo>;
  /**
   * Render the given HTML document to PDF. Uses the pre-compiled styles
   * and loaded fonts from this context.
   * Any additional `<style>` tags in the document are merged with the
   * pre-compiled rules.
   */
  renderToPdf(html: string): Buffer;
  /**
   * Initialize the live DOM from the given HTML. Subsequent calls to
   * `set_content` will patch this DOM in-place instead of re-parsing.
   */
  loadDocument(html: string): void;
  /**
   * Patch the live DOM by replacing the children of the element
   * matching `selector` with the parsed `html_content` fragment.
   * Much faster than re-parsing the entire document.
   */
  setContent(selector: string, htmlContent: string): void;
  /**
   * Query elements from the live DOM. Recomputes styles and layout
   * only if the DOM has been modified since the last query.
   */
  queryLive(selector: string): Array<ElementInfo>;
  /** Serialize the current live DOM back to an HTML string. */
  getContent(): string;
  /** Render the live DOM to PDF. */
  renderLiveToPdf(): Buffer;
}

export interface DataAttribute {
  name: string;
  value: string;
}

export interface ElementInfo {
  x: number;
  y: number;
  width: number;
  height: number;
  attributes: Array<DataAttribute>;
}

export declare function query(
  html: string,
  selector: string
): Array<ElementInfo>;

export declare function renderToPdf(html: string): Buffer;
