/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface DataAttribute {
  name: string;
  value: string;
}

export interface ElementInfo {
  x: number;
  y: number;
  width: number;
  height: number;
  attributes: Array<DataAttribute>;
}

export declare function query(
  html: string,
  selector: string
): Array<ElementInfo>;

export declare function renderToPdf(html: string): Buffer;
