declare namespace NodeJS {
  export interface ProcessEnv {
    NODE_ENV: 'development' | 'production' | 'test';
    IS_INTEGRATION_TEST?: string;
    REACT_APP_VX_DEV?: string;
    REACT_APP_VX_ENABLE_WRITE_IN_ADJUDICATION?: string;
    REACT_APP_VX_ENABLE_ALL_ZERO_SMARTCARD_PIN_GENERATION?: string;
    REACT_APP_VX_ENABLE_LIVECHECK?: string;
    REACT_APP_VX_ENABLE_REACT_QUERY_DEVTOOLS?: string;
    REACT_APP_VX_ENABLE_DEV_DOCK?: string;
    REACT_APP_VX_SKIP_PIN_ENTRY?: string;
    REACT_APP_VX_USE_MOCK_CARDS?: string;
    REACT_APP_VX_USE_MOCK_USB_DRIVE?: string;
    REACT_APP_VX_USE_MOCK_PRINTER?: string;
    REACT_APP_VX_SKIP_CVR_ELECTION_HASH_CHECK?: string;
    REACT_APP_VX_SKIP_SCAN_ELECTION_HASH_CHECK?: string;
    REACT_APP_VX_SKIP_ELECTION_PACKAGE_AUTHENTICATION?: string;
    REACT_APP_VX_SKIP_CAST_VOTE_RECORDS_AUTHENTICATION?: string;
    REACT_APP_VX_CAST_VOTE_RECORD_OPTIMIZATION_EXCLUDE_ORIGINAL_SNAPSHOTS?: string;
    REACT_APP_VX_CAST_VOTE_RECORD_OPTIMIZATION_EXCLUDE_REDUNDANT_METADATA?: string;
    REACT_APP_VX_DISABLE_BALLOT_BOX_CHECK?: string;
    REACT_APP_VX_USE_MOCK_PAPER_HANDLER?: string;
    REACT_APP_VX_ENABLE_CLOUD_TRANSLATION_AND_SPEECH_SYNTHESIS?: string;
    REACT_APP_VX_SCAN_USE_FUJITSU_PRINTER?: string;
    REACT_APP_VX_CONVERTER?: string;
    REACT_APP_VX_SKIP_SYSTEM_AUDIO_SETUP?: string;
    REACT_APP_VX_USE_PDI_SCANNER?: string;
  }
}
