#!/usr/bin/env node

require('esbuild-runner').install({
  type: 'transform',
});

require('./validate_pollbook_package')
  .main(process.argv.slice(2))
  .then((exitCode) => {
    process.exitCode = exitCode;
  });
