/* Generated by res-to-ts. DO NOT EDIT */
/* eslint-disable */
/* istanbul ignore file */

import { Buffer } from 'buffer';
import { mkdtempSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import { join, sep } from 'path';

/**
 * Data of data/electionMinimalExhaustiveSample/precinctScannerCardTallies/pollsPausedSinglePrecinct.json encoded as base64.
 *
 * SHA-256 hash of file data: 9e358a2c3066cfdc57bcc480d34d83e8877645075d4696877b31568ae57010c7
 */
const resourceDataBase64 = 'ewogICJ0YWxseU1hY2hpbmVUeXBlIjogInByZWNpbmN0X3NjYW5uZXIiLAogICJ0b3RhbEJhbGxvdHNTY2FubmVkIjogMCwKICAiaXNMaXZlTW9kZSI6IGZhbHNlLAogICJwb2xsc1RyYW5zaXRpb24iOiAicGF1c2VfcG9sbHMiLAogICJtYWNoaW5lSWQiOiAiMDAwMCIsCiAgInRpbWVTYXZlZCI6IDE2NjU2MTc1NTM4NTEsCiAgInRpbWVQb2xsc1RyYW5zaXRpb25lZCI6IDE2NjU2MTc1NTM4NTEsCiAgInByZWNpbmN0U2VsZWN0aW9uIjogewogICAgImtpbmQiOiAiU2luZ2xlUHJlY2luY3QiLAogICAgInByZWNpbmN0SWQiOiAicHJlY2luY3QtMSIKICB9LAogICJiYWxsb3RDb3VudHMiOiB7CiAgICAiMCxwcmVjaW5jdC0xIjogWzAsIDBdLAogICAgIjEscHJlY2luY3QtMSI6IFswLCAwXSwKICAgICIwLF9fQUxMX1BSRUNJTkNUUyI6IFswLCAwXSwKICAgICIxLF9fQUxMX1BSRUNJTkNUUyI6IFswLCAwXQogIH0sCiAgInRhbGxpZXNCeVByZWNpbmN0IjogewogICAgInByZWNpbmN0LTEiOiBbCiAgICAgIFswLCAwLCAwLCAwLCAwLCAwLCAwXSwKICAgICAgWzAsIDAsIDAsIDAsIDAsIDBdLAogICAgICBbMCwgMCwgMCwgMCwgMCwgMCwgMCwgMF0sCiAgICAgIFswLCAwLCAwLCAwLCAwLCAwLCAwLCAwXSwKICAgICAgWzAsIDAsIDAsIDAsIDAsIDAsIDAsIDAsIDBdLAogICAgICBbMCwgMCwgMCwgMCwgMF0KICAgIF0KICB9LAogICJ0YWxseSI6IFsKICAgIFswLCAwLCAwLCAwLCAwLCAwLCAwXSwKICAgIFswLCAwLCAwLCAwLCAwLCAwXSwKICAgIFswLCAwLCAwLCAwLCAwLCAwLCAwLCAwXSwKICAgIFswLCAwLCAwLCAwLCAwLCAwLCAwLCAwXSwKICAgIFswLCAwLCAwLCAwLCAwLCAwLCAwLCAwLCAwXSwKICAgIFswLCAwLCAwLCAwLCAwXQogIF0KfQo=';

/**
 * MIME type of data/electionMinimalExhaustiveSample/precinctScannerCardTallies/pollsPausedSinglePrecinct.json.
 */
export const mimeType = 'application/json';

/**
 * Path to a file containing this file's contents.
 *
 * SHA-256 hash of file data: 9e358a2c3066cfdc57bcc480d34d83e8877645075d4696877b31568ae57010c7
 */
export function asFilePath(): string {
  const directoryPath = mkdtempSync(tmpdir() + sep);
  const filePath = join(directoryPath, 'pollsPausedSinglePrecinct.json');
  writeFileSync(filePath, asBuffer());
  return filePath;
}

/**
 * Convert to a `data:` URL of data/electionMinimalExhaustiveSample/precinctScannerCardTallies/pollsPausedSinglePrecinct.json, suitable for embedding in HTML.
 *
 * SHA-256 hash of file data: 9e358a2c3066cfdc57bcc480d34d83e8877645075d4696877b31568ae57010c7
 */
export function asDataUrl(): string {
  return `data:${mimeType};base64,${resourceDataBase64}`;
}

/**
 * Raw data of data/electionMinimalExhaustiveSample/precinctScannerCardTallies/pollsPausedSinglePrecinct.json.
 *
 * SHA-256 hash of file data: 9e358a2c3066cfdc57bcc480d34d83e8877645075d4696877b31568ae57010c7
 */
export function asBuffer(): Buffer {
  return Buffer.from(resourceDataBase64, 'base64');
}

/**
 * Text content of data/electionMinimalExhaustiveSample/precinctScannerCardTallies/pollsPausedSinglePrecinct.json.
 *
 * SHA-256 hash of file data: 9e358a2c3066cfdc57bcc480d34d83e8877645075d4696877b31568ae57010c7
 */
export function asText(): string {
  return asBuffer().toString('utf-8');
}