import { electionSampleDefinition } from '@votingworks/fixtures';
import { getAllBallotConfigs } from './get_all_ballot_configs';
import { DEFAULT_LOCALE } from '../config/globals';

jest.mock('@votingworks/types', () => {
  return {
    ...jest.requireActual('@votingworks/types'),
    // mock election hash so snapshots don't change with every change to the election definition
    getDisplayElectionHash: () => '0000000000',
  };
});

test('builds a list of configs for single-language ballots', () => {
  expect(getAllBallotConfigs(electionSampleDefinition, [DEFAULT_LOCALE]))
    .toMatchInlineSnapshot(`
    Array [
      Object {
        "ballotStyleId": "5",
        "contestIds": Array [
          "president",
          "representative-district-6",
          "lieutenant-governor",
          "state-senator-district-31",
          "state-assembly-district-54",
          "county-registrar-of-wills",
          "judicial-robert-demergue",
          "question-a",
          "question-b",
          "proposition-1",
          "102",
        ],
        "filename": "election-0000000000-precinct-north-springfield-id-21-style-5-English-live-absentee.pdf",
        "isAbsentee": true,
        "isLiveMode": true,
        "layoutFilename": "election-0000000000-precinct-north-springfield-id-21-style-5-English-live-absentee-layout.json",
        "locales": Object {
          "primary": "en-US",
          "secondary": undefined,
        },
        "precinctId": "21",
      },
      Object {
        "ballotStyleId": "5",
        "contestIds": Array [
          "president",
          "representative-district-6",
          "lieutenant-governor",
          "state-senator-district-31",
          "state-assembly-district-54",
          "county-registrar-of-wills",
          "judicial-robert-demergue",
          "question-a",
          "question-b",
          "proposition-1",
          "102",
        ],
        "filename": "election-0000000000-precinct-north-springfield-id-21-style-5-English-test-absentee.pdf",
        "isAbsentee": true,
        "isLiveMode": false,
        "layoutFilename": "election-0000000000-precinct-north-springfield-id-21-style-5-English-test-absentee-layout.json",
        "locales": Object {
          "primary": "en-US",
          "secondary": undefined,
        },
        "precinctId": "21",
      },
      Object {
        "ballotStyleId": "5",
        "contestIds": Array [
          "president",
          "representative-district-6",
          "lieutenant-governor",
          "state-senator-district-31",
          "state-assembly-district-54",
          "county-registrar-of-wills",
          "judicial-robert-demergue",
          "question-a",
          "question-b",
          "proposition-1",
          "102",
        ],
        "filename": "election-0000000000-precinct-north-springfield-id-21-style-5-English-live.pdf",
        "isAbsentee": false,
        "isLiveMode": true,
        "layoutFilename": "election-0000000000-precinct-north-springfield-id-21-style-5-English-live-layout.json",
        "locales": Object {
          "primary": "en-US",
          "secondary": undefined,
        },
        "precinctId": "21",
      },
      Object {
        "ballotStyleId": "5",
        "contestIds": Array [
          "president",
          "representative-district-6",
          "lieutenant-governor",
          "state-senator-district-31",
          "state-assembly-district-54",
          "county-registrar-of-wills",
          "judicial-robert-demergue",
          "question-a",
          "question-b",
          "proposition-1",
          "102",
        ],
        "filename": "election-0000000000-precinct-north-springfield-id-21-style-5-English-test.pdf",
        "isAbsentee": false,
        "isLiveMode": false,
        "layoutFilename": "election-0000000000-precinct-north-springfield-id-21-style-5-English-test-layout.json",
        "locales": Object {
          "primary": "en-US",
          "secondary": undefined,
        },
        "precinctId": "21",
      },
      Object {
        "ballotStyleId": "7C",
        "contestIds": Array [
          "primary-constitution-head-of-party",
        ],
        "filename": "election-0000000000-precinct-south-springfield-id-20-style-7C-English-live-absentee.pdf",
        "isAbsentee": true,
        "isLiveMode": true,
        "layoutFilename": "election-0000000000-precinct-south-springfield-id-20-style-7C-English-live-absentee-layout.json",
        "locales": Object {
          "primary": "en-US",
          "secondary": undefined,
        },
        "precinctId": "20",
      },
      Object {
        "ballotStyleId": "7C",
        "contestIds": Array [
          "primary-constitution-head-of-party",
        ],
        "filename": "election-0000000000-precinct-south-springfield-id-20-style-7C-English-test-absentee.pdf",
        "isAbsentee": true,
        "isLiveMode": false,
        "layoutFilename": "election-0000000000-precinct-south-springfield-id-20-style-7C-English-test-absentee-layout.json",
        "locales": Object {
          "primary": "en-US",
          "secondary": undefined,
        },
        "precinctId": "20",
      },
      Object {
        "ballotStyleId": "7C",
        "contestIds": Array [
          "primary-constitution-head-of-party",
        ],
        "filename": "election-0000000000-precinct-south-springfield-id-20-style-7C-English-live.pdf",
        "isAbsentee": false,
        "isLiveMode": true,
        "layoutFilename": "election-0000000000-precinct-south-springfield-id-20-style-7C-English-live-layout.json",
        "locales": Object {
          "primary": "en-US",
          "secondary": undefined,
        },
        "precinctId": "20",
      },
      Object {
        "ballotStyleId": "7C",
        "contestIds": Array [
          "primary-constitution-head-of-party",
        ],
        "filename": "election-0000000000-precinct-south-springfield-id-20-style-7C-English-test.pdf",
        "isAbsentee": false,
        "isLiveMode": false,
        "layoutFilename": "election-0000000000-precinct-south-springfield-id-20-style-7C-English-test-layout.json",
        "locales": Object {
          "primary": "en-US",
          "secondary": undefined,
        },
        "precinctId": "20",
      },
      Object {
        "ballotStyleId": "12",
        "contestIds": Array [
          "president",
          "senator",
          "representative-district-6",
          "governor",
          "lieutenant-governor",
          "secretary-of-state",
          "state-senator-district-31",
          "state-assembly-district-54",
          "county-commissioners",
          "county-registrar-of-wills",
          "city-mayor",
          "city-council",
          "judicial-robert-demergue",
          "judicial-elmer-hull",
          "question-a",
          "question-b",
          "question-c",
          "proposition-1",
          "measure-101",
          "102",
        ],
        "filename": "election-0000000000-precinct-center-springfield-id-23-style-12-English-live-absentee.pdf",
        "isAbsentee": true,
        "isLiveMode": true,
        "layoutFilename": "election-0000000000-precinct-center-springfield-id-23-style-12-English-live-absentee-layout.json",
        "locales": Object {
          "primary": "en-US",
          "secondary": undefined,
        },
        "precinctId": "23",
      },
      Object {
        "ballotStyleId": "12",
        "contestIds": Array [
          "president",
          "senator",
          "representative-district-6",
          "governor",
          "lieutenant-governor",
          "secretary-of-state",
          "state-senator-district-31",
          "state-assembly-district-54",
          "county-commissioners",
          "county-registrar-of-wills",
          "city-mayor",
          "city-council",
          "judicial-robert-demergue",
          "judicial-elmer-hull",
          "question-a",
          "question-b",
          "question-c",
          "proposition-1",
          "measure-101",
          "102",
        ],
        "filename": "election-0000000000-precinct-center-springfield-id-23-style-12-English-test-absentee.pdf",
        "isAbsentee": true,
        "isLiveMode": false,
        "layoutFilename": "election-0000000000-precinct-center-springfield-id-23-style-12-English-test-absentee-layout.json",
        "locales": Object {
          "primary": "en-US",
          "secondary": undefined,
        },
        "precinctId": "23",
      },
      Object {
        "ballotStyleId": "12",
        "contestIds": Array [
          "president",
          "senator",
          "representative-district-6",
          "governor",
          "lieutenant-governor",
          "secretary-of-state",
          "state-senator-district-31",
          "state-assembly-district-54",
          "county-commissioners",
          "county-registrar-of-wills",
          "city-mayor",
          "city-council",
          "judicial-robert-demergue",
          "judicial-elmer-hull",
          "question-a",
          "question-b",
          "question-c",
          "proposition-1",
          "measure-101",
          "102",
        ],
        "filename": "election-0000000000-precinct-center-springfield-id-23-style-12-English-live.pdf",
        "isAbsentee": false,
        "isLiveMode": true,
        "layoutFilename": "election-0000000000-precinct-center-springfield-id-23-style-12-English-live-layout.json",
        "locales": Object {
          "primary": "en-US",
          "secondary": undefined,
        },
        "precinctId": "23",
      },
      Object {
        "ballotStyleId": "12",
        "contestIds": Array [
          "president",
          "senator",
          "representative-district-6",
          "governor",
          "lieutenant-governor",
          "secretary-of-state",
          "state-senator-district-31",
          "state-assembly-district-54",
          "county-commissioners",
          "county-registrar-of-wills",
          "city-mayor",
          "city-council",
          "judicial-robert-demergue",
          "judicial-elmer-hull",
          "question-a",
          "question-b",
          "question-c",
          "proposition-1",
          "measure-101",
          "102",
        ],
        "filename": "election-0000000000-precinct-center-springfield-id-23-style-12-English-test.pdf",
        "isAbsentee": false,
        "isLiveMode": false,
        "layoutFilename": "election-0000000000-precinct-center-springfield-id-23-style-12-English-test-layout.json",
        "locales": Object {
          "primary": "en-US",
          "secondary": undefined,
        },
        "precinctId": "23",
      },
      Object {
        "ballotStyleId": "12",
        "contestIds": Array [
          "president",
          "senator",
          "representative-district-6",
          "governor",
          "lieutenant-governor",
          "secretary-of-state",
          "state-senator-district-31",
          "state-assembly-district-54",
          "county-commissioners",
          "county-registrar-of-wills",
          "city-mayor",
          "city-council",
          "judicial-robert-demergue",
          "judicial-elmer-hull",
          "question-a",
          "question-b",
          "question-c",
          "proposition-1",
          "measure-101",
          "102",
        ],
        "filename": "election-0000000000-precinct-north-springfield-id-21-style-12-English-live-absentee.pdf",
        "isAbsentee": true,
        "isLiveMode": true,
        "layoutFilename": "election-0000000000-precinct-north-springfield-id-21-style-12-English-live-absentee-layout.json",
        "locales": Object {
          "primary": "en-US",
          "secondary": undefined,
        },
        "precinctId": "21",
      },
      Object {
        "ballotStyleId": "12",
        "contestIds": Array [
          "president",
          "senator",
          "representative-district-6",
          "governor",
          "lieutenant-governor",
          "secretary-of-state",
          "state-senator-district-31",
          "state-assembly-district-54",
          "county-commissioners",
          "county-registrar-of-wills",
          "city-mayor",
          "city-council",
          "judicial-robert-demergue",
          "judicial-elmer-hull",
          "question-a",
          "question-b",
          "question-c",
          "proposition-1",
          "measure-101",
          "102",
        ],
        "filename": "election-0000000000-precinct-north-springfield-id-21-style-12-English-test-absentee.pdf",
        "isAbsentee": true,
        "isLiveMode": false,
        "layoutFilename": "election-0000000000-precinct-north-springfield-id-21-style-12-English-test-absentee-layout.json",
        "locales": Object {
          "primary": "en-US",
          "secondary": undefined,
        },
        "precinctId": "21",
      },
      Object {
        "ballotStyleId": "12",
        "contestIds": Array [
          "president",
          "senator",
          "representative-district-6",
          "governor",
          "lieutenant-governor",
          "secretary-of-state",
          "state-senator-district-31",
          "state-assembly-district-54",
          "county-commissioners",
          "county-registrar-of-wills",
          "city-mayor",
          "city-council",
          "judicial-robert-demergue",
          "judicial-elmer-hull",
          "question-a",
          "question-b",
          "question-c",
          "proposition-1",
          "measure-101",
          "102",
        ],
        "filename": "election-0000000000-precinct-north-springfield-id-21-style-12-English-live.pdf",
        "isAbsentee": false,
        "isLiveMode": true,
        "layoutFilename": "election-0000000000-precinct-north-springfield-id-21-style-12-English-live-layout.json",
        "locales": Object {
          "primary": "en-US",
          "secondary": undefined,
        },
        "precinctId": "21",
      },
      Object {
        "ballotStyleId": "12",
        "contestIds": Array [
          "president",
          "senator",
          "representative-district-6",
          "governor",
          "lieutenant-governor",
          "secretary-of-state",
          "state-senator-district-31",
          "state-assembly-district-54",
          "county-commissioners",
          "county-registrar-of-wills",
          "city-mayor",
          "city-council",
          "judicial-robert-demergue",
          "judicial-elmer-hull",
          "question-a",
          "question-b",
          "question-c",
          "proposition-1",
          "measure-101",
          "102",
        ],
        "filename": "election-0000000000-precinct-north-springfield-id-21-style-12-English-test.pdf",
        "isAbsentee": false,
        "isLiveMode": false,
        "layoutFilename": "election-0000000000-precinct-north-springfield-id-21-style-12-English-test-layout.json",
        "locales": Object {
          "primary": "en-US",
          "secondary": undefined,
        },
        "precinctId": "21",
      },
    ]
  `);
});
