#!/usr/bin/env node

import { main } from '../build/printer/cli.js';

main(process.argv)
  .then((code) => {
    process.exitCode = code;
  })
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
