/* eslint-disable */
// Generate a realistic Election definition for Wayne County Nov 2024.
// Uses parsed contest data from /tmp/contest_output.txt for names/candidates,
// and heuristics for district assignment.
//
// Run: node scripts/generate_election_definition.cjs

const fs = require('fs');
const path = require('path');

const dataDir = path.join(__dirname, '../data');
const tallies = require(path.join(dataDir, 'wayne_county_tallies.json'));

// ─── Helpers ─────────────────────────────────────────────────────────────────

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

// ─── Parse contest output file ───────────────────────────────────────────────
// This was generated by an earlier analysis step and has properly-parsed
// multi-line contest headers, candidates, and yes/no detection.

function parseContestOutput(filePath) {
  const text = fs.readFileSync(filePath, 'utf-8');
  const contests = [];

  // Split into PARTISAN and JUDICIAL sections
  const sections = text.split(
    /^={5,}$/m
  );

  for (const section of sections) {
    const blockRegex =
      /--- Contest Block #(\d+) ---\nFull Header: (.+)\n([\s\S]*?)(?=--- Contest Block|Total unique|$)/g;
    let match;
    while ((match = blockRegex.exec(section)) !== null) {
      const header = match[2].trim();
      const body = match[3];

      // Skip continuation blocks (empty body, just a repeated sub-header)
      const hasCandidates = /^\s+-\s+/m.test(body);
      if (!hasCandidates) continue;

      // Determine if it's a multi-contest block
      const individualMatch = body.match(
        /Individual Contests:\n([\s\S]*?)(?=\s+Candidates)/
      );

      let contestNames = [];
      if (individualMatch) {
        const icRegex = /^\s+-\s+\d+\s+(.+)$/gm;
        let m;
        while ((m = icRegex.exec(individualMatch[1])) !== null) {
          contestNames.push(m[1].trim());
        }
      }

      if (contestNames.length === 0) {
        // Single contest - strip leading "N " from header
        const cleanName = header.replace(/^\d+\s+/, '');
        contestNames = [cleanName];
      }

      // Extract candidates
      const candidates = [];
      const candRegex =
        /^\s+-\s+(DEM|REP|LIB|UST|GRN|WCP|NLP|NPA|NP)\s+(.+)$/gm;
      let cm;
      while ((cm = candRegex.exec(body)) !== null) {
        candidates.push({
          party: cm[1] === 'NP' ? null : cm[1],
          name: cm[2].trim().replace(/\s*-\s*$/, ''),
        });
      }

      // Check for Yes/No options
      const yesNoMatch = body.match(/^\s+-\s+(Yes|No)$/m);
      const isYesNo = !!yesNoMatch;
      if (isYesNo) {
        // Count yes/no pairs (for multi-proposal blocks)
        const yesCount = (body.match(/^\s+-\s+Yes$/gm) || []).length;
      }

      // For multi-contest blocks, split candidates between contests
      if (contestNames.length > 1) {
        // Divide candidates roughly equally between contests
        const perContest = Math.ceil(
          candidates.length / contestNames.length
        );
        for (let i = 0; i < contestNames.length; i++) {
          const start = i * perContest;
          const end = Math.min(start + perContest, candidates.length);
          contests.push({
            name: contestNames[i],
            candidates: candidates.slice(start, end),
            isYesNo,
          });
        }
      } else {
        contests.push({
          name: contestNames[0],
          candidates,
          isYesNo,
        });
      }
    }
  }
  return contests;
}

const rawContests = parseContestOutput('/tmp/contest_output.txt');
console.log(`Parsed ${rawContests.length} contests from contest output`);

// Deduplicate by name (keep first occurrence)
const contestMap = new Map();
for (const c of rawContests) {
  if (!contestMap.has(c.name)) {
    contestMap.set(c.name, c);
  }
}
console.log(`${contestMap.size} unique contests after dedup`);

// ─── Group precincts by jurisdiction ─────────────────────────────────────────

const jurisdictions = new Map();
for (const name of Object.keys(tallies)) {
  const commaIdx = name.lastIndexOf(', Precinct');
  if (commaIdx === -1) continue;
  const jur = name.substring(0, commaIdx);
  if (!jurisdictions.has(jur)) jurisdictions.set(jur, []);
  jurisdictions.get(jur).push(name);
}

for (const [, precincts] of jurisdictions) {
  precincts.sort((a, b) => a.localeCompare(b));
}

const sortedJurisdictions = [...jurisdictions.entries()].sort(([a], [b]) =>
  a.localeCompare(b)
);

// ─── Classify contests by scope ──────────────────────────────────────────────

const COUNTY_WIDE_DISTRICT = 'wayne-county';

// Patterns for county-wide contests (all 805 precincts see these)
const COUNTY_WIDE_PATTERNS = [
  /^Straight Party Ticket$/,
  /^Electors of President/,
  /^United States Senator$/,
  /^Member of the State Board of Education$/,
  /^Regent of the University of Michigan$/,
  /^Trustee of Michigan State University$/,
  /^Governor of Wayne State University$/,
  /^Prosecuting Attorney$/,
  /^Sheriff$/,
  /^Clerk$/,
  /^Treasurer$/,
  /^Register of Deeds$/,
  /^Justice of the Supreme Court/,
  /^Justice of Supreme Court/,
  /^Judge of Court of Appeals 1st District/,
  /^Judge of Circuit Court 3rd Circuit/,
  /^Judge of Probate Court(?!.*MACOMB)/,
  /^Wayne RESA/,
  /^Detroit School District - Proposal S/,
];

// Patterns for district-specific contests
const DISTRICT_PATTERNS = [
  {
    regex: /Representative in Congress for (\d+)(?:th|st|nd|rd) District/,
    makeId: (m) => `us-congress-${m[1]}`,
    makeName: (m) => `U.S. Congressional District ${m[1]}`,
  },
  {
    regex:
      /Representative in State Legislature for (\d+)(?:th|st|nd|rd) District/,
    makeId: (m) => `state-house-${m[1]}`,
    makeName: (m) => `State House District ${m[1]}`,
  },
  {
    regex: /County Commissioner (\d+)(?:th|st|nd|rd) District$/,
    makeId: (m) => `county-comm-${m[1]}`,
    makeName: (m) => `County Commissioner District ${m[1]}`,
  },
];

// Jurisdiction-specific contest patterns
function matchJurisdiction(contestName) {
  // Township matches
  const twpPatterns = [
    /for (Canton Township)/,
    /for (Charter Township of \w+)/,
    /for (Redford Township)/,
    /for (Township of Sumpter)/,
    /for (Van Buren Township)/,
    /for (Plymouth Township)/,
    /for (Grosse Ile Township)/,
    /(Redford Township)$/,
  ];
  for (const p of twpPatterns) {
    const m = contestName.match(p);
    if (m) return m[1];
  }

  // City matches
  const cityPattern = /(?:City of |City - |City (?=-))([\w\s]+?)(?:\s*[-,]|\s+Proposed|\s+Proposal|\s+Local|\s+Senior|\s+Charter|\s+City)/;
  const cm = contestName.match(cityPattern);
  if (cm) return 'City of ' + cm[1].trim();

  // Direct city name matches for specific patterns
  const directCityPatterns = [
    /^(?:Mayor|Clerk|Treasurer|Assessor|City Council) - (City of \w[\w\s]*?)$/,
  ];
  for (const p of directCityPatterns) {
    const m = contestName.match(p);
    if (m) return m[1].trim();
  }

  // School district → map to jurisdiction
  const schoolToJurisdiction = {
    'Airport Community Schools': ['Ash Township', 'City of Flat Rock'],
    'Allen Park Public Schools': ['City of Allen Park'],
    'Clarenceville School District': ['City of Livonia', 'City of Farmington Hills'],
    'Crestwood School District': ['City of Dearborn Heights'],
    'Dearborn Public Schools': ['City of Dearborn'],
    'Dearborn Heights School District No. 7': ['City of Dearborn Heights'],
    'Detroit Public Schools Community District': ['City of Detroit'],
    'Ecorse Public Schools': ['City of Ecorse'],
    'Flat Rock Community Schools': ['City of Flat Rock'],
    'Garden City Public Schools': ['City of Garden City'],
    'Gibraltar School District': ['City of Gibraltar', 'City of Woodhaven', 'City of Flat Rock'],
    'Grosse Ile Township Schools': ['Charter Township of Huron'],
    'Grosse Pointe Public Schools': [
      'City of Grosse Pointe',
      'City of Grosse Pointe Farms',
      'City of Grosse Pointe Park',
      'City of Grosse Pointe Woods',
      'City of Harper Woods',
      'Shores, a Michigan City',
    ],
    'Hamtramck Public Schools': ['City of Hamtramck'],
    'Harper Woods School District': ['City of Harper Woods'],
    'Highland Park Public Schools': ['City of Highland Park'],
    'Huron School District': ['Charter Township of Huron'],
    'Lincoln Consolidated Schools': ['City of Belleville', 'Ypsilanti Township'],
    'Lincoln Park Public Schools': ['City of Taylor'],
    'Livonia Public Schools': ['City of Livonia'],
    'Melvindale-North Allen Park Public Schools': ['City of Melvindale'],
    'Northville Public Schools': ['Charter Township of Northville', 'City of Northville'],
    'Plymouth-Canton Community Schools': ['Canton Township', 'City of Plymouth'],
    'Redford Union School District': ['Redford Township'],
    'River Rouge School District': ['City of Ecorse'],
    'Riverview Community Schools': ['City of Riverview'],
    'Romulus Community Schools': ['City of Romulus'],
    'South Redford School District': ['Redford Township'],
    'Southgate Community Schools': ['City of Southgate'],
    'Taylor School District': ['City of Taylor'],
    'Trenton Public Schools': ['City of Trenton'],
    'Van Buren Public Schools': ['Canton Township', 'City of Belleville'],
    'Wayne-Westland Community Schools': ['City of Westland', 'City of Wayne', 'Canton Township'],
    'Westwood Community Schools': ['City of Dearborn Heights'],
    'Woodhaven-Brownstown School District': ['City of Woodhaven', 'Charter Township of Brownstown'],
    'Wyandotte Public Schools': ['City of Wyandotte'],
    'Washtenaw Intermediate School District': ['Ypsilanti Township', 'Salem Township', 'Superior Township'],
  };

  for (const [school, jurs] of Object.entries(schoolToJurisdiction)) {
    if (contestName.includes(school)) return jurs;
  }

  // Library → jurisdiction
  const libraryToJurisdiction = {
    'Belleville Area District Library': ['City of Belleville'],
    'Northville District Library': ['Charter Township of Northville', 'City of Northville'],
    'Plymouth District Library': ['City of Plymouth'],
    'Garden City': ['City of Garden City'],
  };
  for (const [lib, jurs] of Object.entries(libraryToJurisdiction)) {
    if (contestName.includes(lib) || (contestName.includes('Library') && contestName.includes(lib))) {
      return jurs;
    }
  }
  if (contestName.includes('Library Board Director')) return 'City of Detroit';

  // Community college → broad districts
  if (contestName.includes('Wayne County Community College')) return null; // county-wide
  if (contestName.includes('Schoolcraft Community College'))
    return ['City of Livonia', 'Canton Township', 'City of Plymouth', 'City of Northville', 'Charter Township of Northville'];

  // Ballot proposals
  if (contestName.includes('Grosse Ile Township')) return 'Charter Township of Huron';
  if (contestName.includes('Parks Commission for Redford')) return 'Redford Township';

  return null;
}

// ─── Build districts and contest assignments ─────────────────────────────────

const districts = [{ id: COUNTY_WIDE_DISTRICT, name: 'Wayne County' }];
const jurisdictionDistrictMap = new Map();

for (const [jur] of sortedJurisdictions) {
  const id = slugify(jur);
  jurisdictionDistrictMap.set(jur, id);
  districts.push({ id, name: jur });
}

// Additional districts for congressional, state leg, county commissioner
const additionalDistricts = new Map();
const allDistrictIds = new Set(districts.map((d) => d.id));
function getOrCreateDistrict(id, name) {
  if (!allDistrictIds.has(id)) {
    allDistrictIds.add(id);
    additionalDistricts.set(id, { id, name });
    districts.push({ id, name });
  }
  return id;
}

// Assign each contest to a district
const contestDistrictAssignments = new Map(); // contestName -> districtId
// Also track which districts need to be added to which precincts
const extraPrecinctDistricts = new Map(); // precinctName -> Set<districtId>

function addDistrictToJurisdiction(jur, districtId) {
  const precincts = jurisdictions.get(jur);
  if (!precincts) return;
  for (const p of precincts) {
    if (!extraPrecinctDistricts.has(p)) extraPrecinctDistricts.set(p, new Set());
    extraPrecinctDistricts.get(p).add(districtId);
  }
}

// Skip MACOMB contests entirely
const SKIP = (name) => name.includes('MACOMB');

for (const [contestName] of contestMap) {
  if (SKIP(contestName)) continue;

  // Check county-wide
  if (COUNTY_WIDE_PATTERNS.some((p) => p.test(contestName))) {
    contestDistrictAssignments.set(contestName, COUNTY_WIDE_DISTRICT);
    continue;
  }

  // Check district-specific
  let matched = false;
  for (const dp of DISTRICT_PATTERNS) {
    const m = contestName.match(dp.regex);
    if (m) {
      const dId = getOrCreateDistrict(dp.makeId(m), dp.makeName(m));
      contestDistrictAssignments.set(contestName, dId);
      matched = true;
      break;
    }
  }
  if (matched) continue;

  // Check jurisdiction-specific
  const jur = matchJurisdiction(contestName);
  if (jur) {
    if (typeof jur === 'string') {
      const dId = jurisdictionDistrictMap.get(jur);
      if (dId) {
        contestDistrictAssignments.set(contestName, dId);
        continue;
      }
    } else if (Array.isArray(jur)) {
      if (jur.length === 1) {
        // Single jurisdiction in array form
        const dId = jurisdictionDistrictMap.get(jur[0]);
        if (dId) {
          contestDistrictAssignments.set(contestName, dId);
          continue;
        }
      }
      // Multi-jurisdiction: create a combined district
      // Use contest name as district name to ensure uniqueness
      const combinedId = slugify(contestName).substring(0, 60);
      const combinedName = contestName;
      getOrCreateDistrict(combinedId, combinedName);
      contestDistrictAssignments.set(contestName, combinedId);
      // Add this district to all precincts in these jurisdictions
      for (const j of jur) {
        addDistrictToJurisdiction(j, combinedId);
      }
      continue;
    }
  }

  // Wayne County Community College → county-wide
  if (contestName.includes('Wayne County Community College')) {
    contestDistrictAssignments.set(contestName, COUNTY_WIDE_DISTRICT);
    continue;
  }

  // Fallback: try to find jurisdiction from contest name keywords
  let found = false;
  for (const [jurName, jurId] of jurisdictionDistrictMap) {
    if (
      contestName.includes(jurName) ||
      (jurName.startsWith('City of ') &&
        contestName.includes(jurName.replace('City of ', '')))
    ) {
      contestDistrictAssignments.set(contestName, jurId);
      found = true;
      break;
    }
  }
  if (found) continue;

  // Last resort: put on county-wide
  console.log(`  Warning: no district match for: ${contestName}`);
  contestDistrictAssignments.set(contestName, COUNTY_WIDE_DISTRICT);
}

console.log(
  `Assigned ${contestDistrictAssignments.size} contests to districts`
);

// ─── Build precincts ─────────────────────────────────────────────────────────

const precincts = [];
for (const [jur, names] of sortedJurisdictions) {
  const jurDistrictId = jurisdictionDistrictMap.get(jur);
  for (const name of names) {
    const dIds = new Set([COUNTY_WIDE_DISTRICT, jurDistrictId]);
    const extras = extraPrecinctDistricts.get(name);
    if (extras) {
      for (const d of extras) dIds.add(d);
    }
    precincts.push({
      id: slugify(name),
      name,
      districtIds: [...dIds].sort(),
    });
  }
}

// We also need to assign congressional/state leg/commissioner districts to precincts.
// Since we don't have the exact mapping, we'll add them based on known geography.
// For the election definition to be valid, each district just needs at least one
// precinct assigned to it. We'll assign all non-jurisdiction district contests
// to precinct groups based on approximate geographic knowledge.

// Congressional districts in Wayne County:
// 6th: western Wayne (Livonia, Plymouth, Canton, Northville, etc.)
// 10th: northern (some Macomb overlap)
// 12th: Dearborn, Dearborn Heights, Westland, etc.
// 13th: Detroit, Highland Park, Hamtramck, etc.
const congressionalMapping = {
  'us-congress-6': [
    'City of Livonia', 'Canton Township', 'City of Plymouth',
    'Charter Township of Northville', 'City of Northville',
    'City of Westland', 'City of Wayne', 'City of Romulus',
    'City of Belleville', 'City of Flat Rock', 'City of Rockwood',
  ],
  'us-congress-10': ['City of Novi', 'Novi Township', 'Lyon Township'],
  'us-congress-12': [
    'City of Dearborn', 'City of Dearborn Heights', 'City of Garden City',
    'City of Melvindale', 'City of Allen Park', 'City of Southgate',
    'City of Taylor', 'City of Wyandotte', 'City of Ecorse',
    'City of Riverview', 'City of Trenton', 'City of Woodhaven',
    'City of Gibraltar', 'Charter Township of Brownstown',
    'Redford Township', 'Charter Township of Huron',
    'Township of Sumpter', 'Berlin Township', 'Ash Township',
  ],
  'us-congress-13': [
    'City of Detroit', 'City of Highland Park', 'City of Hamtramck',
    'City of Harper Woods', 'City of Grosse Pointe',
    'City of Grosse Pointe Farms', 'City of Grosse Pointe Park',
    'City of Grosse Pointe Woods', 'Shores, a Michigan City',
    'City of Farmington Hills',
  ],
};

for (const [distId, jurs] of Object.entries(congressionalMapping)) {
  if (!additionalDistricts.has(distId)) continue;
  for (const jur of jurs) {
    const jurPrecincts = jurisdictions.get(jur);
    if (!jurPrecincts) continue;
    for (const p of jurPrecincts) {
      const precinct = precincts.find((pr) => pr.name === p);
      if (precinct && !precinct.districtIds.includes(distId)) {
        precinct.districtIds.push(distId);
        precinct.districtIds.sort();
      }
    }
  }
}

// For state house and county commissioner districts, assign to jurisdiction groups.
// This is approximate — in reality these cross jurisdiction boundaries.
// We'll distribute them across jurisdictions to ensure every district has precincts.
const stateHouseMapping = {
  'state-house-1': ['City of Detroit'],
  'state-house-2': ['City of Detroit'],
  'state-house-3': ['City of Dearborn'],
  'state-house-4': ['City of Detroit'],
  'state-house-5': ['City of Detroit'],
  'state-house-7': ['City of Detroit'],
  'state-house-8': ['City of Detroit'],
  'state-house-9': ['City of Detroit'],
  'state-house-10': ['City of Highland Park', 'City of Hamtramck'],
  'state-house-11': ['City of Harper Woods', 'City of Grosse Pointe', 'City of Grosse Pointe Farms', 'City of Grosse Pointe Park', 'City of Grosse Pointe Woods', 'Shores, a Michigan City'],
  'state-house-12': ['City of Dearborn Heights', 'City of Garden City'],
  'state-house-15': ['Redford Township'],
  'state-house-16': ['City of Detroit'],
  'state-house-17': ['City of Livonia'],
  'state-house-22': ['Canton Township', 'City of Plymouth'],
  'state-house-23': ['City of Belleville', 'Ypsilanti Township', 'Superior Township', 'Salem Township'],
  'state-house-24': ['City of Allen Park', 'City of Melvindale', 'City of Southgate'],
  'state-house-25': ['City of Taylor'],
  'state-house-26': ['City of Wyandotte', 'City of Riverview', 'City of Trenton'],
  'state-house-27': ['City of Woodhaven', 'Charter Township of Brownstown', 'City of Flat Rock', 'City of Rockwood', 'City of Gibraltar'],
  'state-house-28': ['City of Romulus', 'Township of Sumpter', 'Ash Township', 'Berlin Township'],
  'state-house-29': ['City of Westland', 'City of Wayne'],
  'state-house-31': ['Charter Township of Huron', 'Charter Township of Northville', 'City of Northville'],
};

for (const [distId, jurs] of Object.entries(stateHouseMapping)) {
  if (!additionalDistricts.has(distId)) continue;
  for (const jur of jurs) {
    const jurPrecincts = jurisdictions.get(jur);
    if (!jurPrecincts) continue;
    for (const p of jurPrecincts) {
      const precinct = precincts.find((pr) => pr.name === p);
      if (precinct && !precinct.districtIds.includes(distId)) {
        precinct.districtIds.push(distId);
        precinct.districtIds.sort();
      }
    }
  }
}

// County commissioner districts
const commissionerMapping = {
  'county-comm-1': ['City of Detroit'],
  'county-comm-2': ['City of Detroit'],
  'county-comm-3': ['City of Detroit'],
  'county-comm-4': ['City of Detroit'],
  'county-comm-5': ['City of Detroit'],
  'county-comm-6': ['City of Detroit'],
  'county-comm-7': ['City of Detroit'],
  'county-comm-8': ['City of Dearborn', 'City of Dearborn Heights'],
  'county-comm-9': ['City of Livonia'],
  'county-comm-10': ['City of Westland', 'City of Wayne', 'City of Garden City'],
  'county-comm-11': ['Redford Township', 'City of Highland Park', 'City of Hamtramck'],
  'county-comm-12': ['City of Taylor', 'City of Romulus', 'City of Southgate', 'City of Allen Park'],
  'county-comm-13': ['City of Wyandotte', 'City of Riverview', 'City of Trenton', 'City of Woodhaven', 'City of Ecorse', 'City of Melvindale'],
  'county-comm-14': ['Canton Township', 'City of Plymouth', 'Charter Township of Northville', 'City of Northville'],
  'county-comm-15': ['Charter Township of Brownstown', 'City of Gibraltar', 'City of Flat Rock', 'City of Rockwood', 'Charter Township of Huron', 'Township of Sumpter'],
};

for (const [distId, jurs] of Object.entries(commissionerMapping)) {
  if (!additionalDistricts.has(distId)) continue;
  for (const jur of jurs) {
    const jurPrecincts = jurisdictions.get(jur);
    if (!jurPrecincts) continue;
    for (const p of jurPrecincts) {
      const precinct = precincts.find((pr) => pr.name === p);
      if (precinct && !precinct.districtIds.includes(distId)) {
        precinct.districtIds.push(distId);
        precinct.districtIds.sort();
      }
    }
  }
}

// ─── Build ballot styles ─────────────────────────────────────────────────────

// Group precincts by their district set
const districtSetToPrecincts = new Map();
for (const precinct of precincts) {
  const key = precinct.districtIds.join('|');
  if (!districtSetToPrecincts.has(key)) districtSetToPrecincts.set(key, []);
  districtSetToPrecincts.get(key).push(precinct);
}

const ballotStyles = [];
let bsCounter = 0;
for (const [districtKey, bsPrecincts] of districtSetToPrecincts) {
  bsCounter++;
  const districtIdList = districtKey.split('|');
  const firstName = bsPrecincts[0].name;
  const jurMatch = firstName.match(/^(.+),\s*Precinct/);
  const jurSlug = jurMatch ? slugify(jurMatch[1]) : `style-${bsCounter}`;
  const bsId =
    bsPrecincts.length === jurisdictions.get(jurMatch?.[1])?.length
      ? jurSlug
      : `${jurSlug}-${bsCounter}`;

  ballotStyles.push({
    id: `${bsId}_en`,
    groupId: bsId,
    precincts: bsPrecincts.map((p) => p.id),
    districts: districtIdList,
    languages: ['en'],
  });
}

console.log(`Created ${ballotStyles.length} ballot styles`);

// ─── Build contests ──────────────────────────────────────────────────────────

const KNOWN_PARTIES = {
  DEM: { id: 'DEM', name: 'Democratic', fullName: 'Democratic Party', abbrev: 'D' },
  REP: { id: 'REP', name: 'Republican', fullName: 'Republican Party', abbrev: 'R' },
  LIB: { id: 'LIB', name: 'Libertarian', fullName: 'Libertarian Party', abbrev: 'L' },
  UST: { id: 'UST', name: 'U.S. Taxpayers', fullName: 'U.S. Taxpayers Party', abbrev: 'U' },
  GRN: { id: 'GRN', name: 'Green', fullName: 'Green Party', abbrev: 'G' },
  WCP: { id: 'WCP', name: 'Working Class', fullName: 'Working Class Party', abbrev: 'W' },
  NLP: { id: 'NLP', name: 'Natural Law', fullName: 'Natural Law Party', abbrev: 'N' },
  NPA: { id: 'NPA', name: 'No Party Affiliation', fullName: 'No Party Affiliation', abbrev: 'I' },
};

const MULTI_SEAT_PATTERNS = [
  { pattern: /^Straight Party Ticket$/, seats: 1 },
  { pattern: /^Member of the State Board of Education$/, seats: 2 },
  { pattern: /^Regent of the University/, seats: 2 },
  { pattern: /^Trustee of Michigan State/, seats: 2 },
  { pattern: /^Governor of Wayne State/, seats: 2 },
  { pattern: /^Judge of Circuit Court 3rd Circuit, Incumbent Position$/, seats: 10 },
  { pattern: /^Judge of Circuit Court 16th Circuit, Incumbent/, seats: 4 },
  { pattern: /^Judge of District Court, 36th District Incumbent Position$/, seats: 9 },
  { pattern: /^Trustee for/, seats: 4 },
  { pattern: /^City Council/, seats: 3 },
  { pattern: /^Board Member.*Schools?/, seats: 2 },
  { pattern: /^Board Member.*Library/, seats: 2 },
  { pattern: /^Board Member.*College/, seats: 2 },
  { pattern: /^Board of Trustees/, seats: 2 },
  { pattern: /^Library Board/, seats: 3 },
  { pattern: /^Parks Commission/, seats: 3 },
];

function getSeats(name) {
  for (const { pattern, seats } of MULTI_SEAT_PATTERNS) {
    if (pattern.test(name)) return seats;
  }
  return 1;
}

const usedPartyIds = new Set();
const electionContests = [];
let candidateIdCounter = 0;

// Get all districts referenced by ballot styles
const referencedDistricts = new Set();
for (const bs of ballotStyles) {
  for (const d of bs.districts) referencedDistricts.add(d);
}

for (const [contestName, contestData] of contestMap) {
  if (SKIP(contestName)) continue;

  const districtId = contestDistrictAssignments.get(contestName);
  if (!districtId || !referencedDistricts.has(districtId)) continue;

  const id = slugify(contestName);

  if (contestData.isYesNo) {
    electionContests.push({
      id,
      districtId,
      title: contestName,
      type: 'yesno',
      description: `<p>${contestName}</p>`,
      yesOption: { id: `${id}-yes`, label: 'Yes' },
      noOption: { id: `${id}-no`, label: 'No' },
    });
  } else {
    const seats = getSeats(contestName);
    const candidates = [];
    const seenCandIds = new Set();

    for (const c of contestData.candidates) {
      let candId = slugify(c.name) || `candidate-${++candidateIdCounter}`;
      if (seenCandIds.has(candId)) {
        candId = `${candId}-${++candidateIdCounter}`;
      }
      seenCandIds.add(candId);

      const cand = { id: candId, name: c.name };
      if (c.party) {
        cand.partyIds = [c.party];
        usedPartyIds.add(c.party);
      }
      candidates.push(cand);
    }

    if (candidates.length === 0) {
      candidates.push({ id: `${id}-placeholder`, name: 'Candidate' });
    }

    const allowWriteIns = candidates.some((c) => c.partyIds);

    electionContests.push({
      id,
      districtId,
      title: contestName,
      type: 'candidate',
      seats,
      candidates,
      allowWriteIns,
    });
  }
}

console.log(`Created ${electionContests.length} contests`);

// Filter parties to only those used
const usedParties = Object.values(KNOWN_PARTIES).filter((p) =>
  usedPartyIds.has(p.id)
);

// Filter districts to only those referenced by ballot styles
const filteredDistricts = districts.filter((d) => referencedDistricts.has(d.id));

// ─── Assemble and write ──────────────────────────────────────────────────────

const election = {
  ballotLayout: { paperSize: 'letter', metadataEncoding: 'qr-code' },
  ballotStrings: {},
  ballotStyles,
  contests: electionContests,
  county: { id: 'wayne-county', name: 'Wayne County' },
  date: '2024-11-05',
  districts: filteredDistricts,
  id: 'wayne-county-general-2024',
  parties: usedParties,
  precincts,
  seal: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><circle cx="50" cy="50" r="45" fill="none" stroke="#333" stroke-width="2"/><text x="50" y="35" text-anchor="middle" font-size="8" font-family="serif">Wayne County</text><text x="50" y="50" text-anchor="middle" font-size="6" font-family="serif">Michigan</text><text x="50" y="65" text-anchor="middle" font-size="6" font-family="serif">Official Seal</text></svg>',
  state: 'Michigan',
  title: 'General Election',
  type: 'general',
};

const outDir = path.join(dataDir, 'electionWayneCountyGeneral2024');
fs.mkdirSync(outDir, { recursive: true });
const outPath = path.join(outDir, 'electionBase.json');
const json = JSON.stringify(election, null, 2);
fs.writeFileSync(outPath, json);

console.log(`\nGenerated: ${outPath}`);
console.log(`File size: ${(json.length / 1024).toFixed(1)} KB`);
console.log(`Precincts: ${precincts.length}`);
console.log(`Districts: ${filteredDistricts.length}`);
console.log(`Ballot styles: ${ballotStyles.length}`);
console.log(`Contests: ${electionContests.length}`);
console.log(`  Candidate: ${electionContests.filter((c) => c.type === 'candidate').length}`);
console.log(`  Yes/No: ${electionContests.filter((c) => c.type === 'yesno').length}`);
console.log(`Parties: ${usedParties.length}`);
