/** Stub for 'fs' module, generated by script/build-stubs. DO NOT EDIT */
/* eslint-disable */
/* istanbul ignore file */

function __stubFnDoNotCall(): never {
  throw new Error('this function is a stub and should never be called');
}
/** Stub for appendFile */
export const appendFile = __stubFnDoNotCall;
/** Stub for appendFileSync */
export const appendFileSync = __stubFnDoNotCall;
/** Stub for access */
export const access = __stubFnDoNotCall;
/** Stub for accessSync */
export const accessSync = __stubFnDoNotCall;
/** Stub for chown */
export const chown = __stubFnDoNotCall;
/** Stub for chownSync */
export const chownSync = __stubFnDoNotCall;
/** Stub for chmod */
export const chmod = __stubFnDoNotCall;
/** Stub for chmodSync */
export const chmodSync = __stubFnDoNotCall;
/** Stub for close */
export const close = __stubFnDoNotCall;
/** Stub for closeSync */
export const closeSync = __stubFnDoNotCall;
/** Stub for copyFile */
export const copyFile = __stubFnDoNotCall;
/** Stub for copyFileSync */
export const copyFileSync = __stubFnDoNotCall;
/** Stub for cp */
export const cp = __stubFnDoNotCall;
/** Stub for cpSync */
export const cpSync = __stubFnDoNotCall;
/** Stub for createReadStream */
export const createReadStream = __stubFnDoNotCall;
/** Stub for createWriteStream */
export const createWriteStream = __stubFnDoNotCall;
/** Stub for exists */
export const exists = __stubFnDoNotCall;
/** Stub for existsSync */
export const existsSync = __stubFnDoNotCall;
/** Stub for fchown */
export const fchown = __stubFnDoNotCall;
/** Stub for fchownSync */
export const fchownSync = __stubFnDoNotCall;
/** Stub for fchmod */
export const fchmod = __stubFnDoNotCall;
/** Stub for fchmodSync */
export const fchmodSync = __stubFnDoNotCall;
/** Stub for fdatasync */
export const fdatasync = __stubFnDoNotCall;
/** Stub for fdatasyncSync */
export const fdatasyncSync = __stubFnDoNotCall;
/** Stub for fstat */
export const fstat = __stubFnDoNotCall;
/** Stub for fstatSync */
export const fstatSync = __stubFnDoNotCall;
/** Stub for fsync */
export const fsync = __stubFnDoNotCall;
/** Stub for fsyncSync */
export const fsyncSync = __stubFnDoNotCall;
/** Stub for ftruncate */
export const ftruncate = __stubFnDoNotCall;
/** Stub for ftruncateSync */
export const ftruncateSync = __stubFnDoNotCall;
/** Stub for futimes */
export const futimes = __stubFnDoNotCall;
/** Stub for futimesSync */
export const futimesSync = __stubFnDoNotCall;
/** Stub for lchown */
export const lchown = __stubFnDoNotCall;
/** Stub for lchownSync */
export const lchownSync = __stubFnDoNotCall;
/** Stub for lchmod */
export const lchmod = undefined;
/** Stub for lchmodSync */
export const lchmodSync = undefined;
/** Stub for link */
export const link = __stubFnDoNotCall;
/** Stub for linkSync */
export const linkSync = __stubFnDoNotCall;
/** Stub for lstat */
export const lstat = __stubFnDoNotCall;
/** Stub for lstatSync */
export const lstatSync = __stubFnDoNotCall;
/** Stub for lutimes */
export const lutimes = __stubFnDoNotCall;
/** Stub for lutimesSync */
export const lutimesSync = __stubFnDoNotCall;
/** Stub for mkdir */
export const mkdir = __stubFnDoNotCall;
/** Stub for mkdirSync */
export const mkdirSync = __stubFnDoNotCall;
/** Stub for mkdtemp */
export const mkdtemp = __stubFnDoNotCall;
/** Stub for mkdtempSync */
export const mkdtempSync = __stubFnDoNotCall;
/** Stub for open */
export const open = __stubFnDoNotCall;
/** Stub for openSync */
export const openSync = __stubFnDoNotCall;
/** Stub for opendir */
export const opendir = __stubFnDoNotCall;
/** Stub for opendirSync */
export const opendirSync = __stubFnDoNotCall;
/** Stub for readdir */
export const readdir = __stubFnDoNotCall;
/** Stub for readdirSync */
export const readdirSync = __stubFnDoNotCall;
/** Stub for read */
export const read = __stubFnDoNotCall;
/** Stub for readSync */
export const readSync = __stubFnDoNotCall;
/** Stub for readv */
export const readv = __stubFnDoNotCall;
/** Stub for readvSync */
export const readvSync = __stubFnDoNotCall;
/** Stub for readFile */
export const readFile = __stubFnDoNotCall;
/** Stub for readFileSync */
export const readFileSync = __stubFnDoNotCall;
/** Stub for readlink */
export const readlink = __stubFnDoNotCall;
/** Stub for readlinkSync */
export const readlinkSync = __stubFnDoNotCall;
/** Stub for realpath */
export const realpath = __stubFnDoNotCall;
/** Stub for realpathSync */
export const realpathSync = __stubFnDoNotCall;
/** Stub for rename */
export const rename = __stubFnDoNotCall;
/** Stub for renameSync */
export const renameSync = __stubFnDoNotCall;
/** Stub for rm */
export const rm = __stubFnDoNotCall;
/** Stub for rmSync */
export const rmSync = __stubFnDoNotCall;
/** Stub for rmdir */
export const rmdir = __stubFnDoNotCall;
/** Stub for rmdirSync */
export const rmdirSync = __stubFnDoNotCall;
/** Stub for stat */
export const stat = __stubFnDoNotCall;
/** Stub for statSync */
export const statSync = __stubFnDoNotCall;
/** Stub for symlink */
export const symlink = __stubFnDoNotCall;
/** Stub for symlinkSync */
export const symlinkSync = __stubFnDoNotCall;
/** Stub for truncate */
export const truncate = __stubFnDoNotCall;
/** Stub for truncateSync */
export const truncateSync = __stubFnDoNotCall;
/** Stub for unwatchFile */
export const unwatchFile = __stubFnDoNotCall;
/** Stub for unlink */
export const unlink = __stubFnDoNotCall;
/** Stub for unlinkSync */
export const unlinkSync = __stubFnDoNotCall;
/** Stub for utimes */
export const utimes = __stubFnDoNotCall;
/** Stub for utimesSync */
export const utimesSync = __stubFnDoNotCall;
/** Stub for watch */
export const watch = __stubFnDoNotCall;
/** Stub for watchFile */
export const watchFile = __stubFnDoNotCall;
/** Stub for writeFile */
export const writeFile = __stubFnDoNotCall;
/** Stub for writeFileSync */
export const writeFileSync = __stubFnDoNotCall;
/** Stub for write */
export const write = __stubFnDoNotCall;
/** Stub for writeSync */
export const writeSync = __stubFnDoNotCall;
/** Stub for writev */
export const writev = __stubFnDoNotCall;
/** Stub for writevSync */
export const writevSync = __stubFnDoNotCall;
/** Stub for Dir */
export const Dir = __stubFnDoNotCall;
/** Stub for Dirent */
export const Dirent = __stubFnDoNotCall;
/** Stub for Stats */
export const Stats = __stubFnDoNotCall;
/** Stub for ReadStream */
export const ReadStream = __stubFnDoNotCall;
/** Stub for WriteStream */
export const WriteStream = __stubFnDoNotCall;
/** Stub for FileReadStream */
export const FileReadStream = __stubFnDoNotCall;
/** Stub for FileWriteStream */
export const FileWriteStream = __stubFnDoNotCall;
/** Stub for _toUnixTimestamp */
export const _toUnixTimestamp = __stubFnDoNotCall;
/** Stub for F_OK */
export const F_OK = 0;
/** Stub for R_OK */
export const R_OK = 4;
/** Stub for W_OK */
export const W_OK = 2;
/** Stub for X_OK */
export const X_OK = 1;
/** Stub for constants */
export const constants = {
  UV_FS_SYMLINK_DIR: 1,
  UV_FS_SYMLINK_JUNCTION: 2,
  O_RDONLY: 0,
  O_WRONLY: 1,
  O_RDWR: 2,
  UV_DIRENT_UNKNOWN: 0,
  UV_DIRENT_FILE: 1,
  UV_DIRENT_DIR: 2,
  UV_DIRENT_LINK: 3,
  UV_DIRENT_FIFO: 4,
  UV_DIRENT_SOCKET: 5,
  UV_DIRENT_CHAR: 6,
  UV_DIRENT_BLOCK: 7,
  S_IFMT: 61440,
  S_IFREG: 32768,
  S_IFDIR: 16384,
  S_IFCHR: 8192,
  S_IFBLK: 24576,
  S_IFIFO: 4096,
  S_IFLNK: 40960,
  S_IFSOCK: 49152,
  O_CREAT: 64,
  O_EXCL: 128,
  UV_FS_O_FILEMAP: 0,
  O_NOCTTY: 256,
  O_TRUNC: 512,
  O_APPEND: 1024,
  O_DIRECTORY: 16384,
  O_NOATIME: 262144,
  O_NOFOLLOW: 32768,
  O_SYNC: 1052672,
  O_DSYNC: 4096,
  O_DIRECT: 65536,
  O_NONBLOCK: 2048,
  S_IRWXU: 448,
  S_IRUSR: 256,
  S_IWUSR: 128,
  S_IXUSR: 64,
  S_IRWXG: 56,
  S_IRGRP: 32,
  S_IWGRP: 16,
  S_IXGRP: 8,
  S_IRWXO: 7,
  S_IROTH: 4,
  S_IWOTH: 2,
  S_IXOTH: 1,
  F_OK: 0,
  R_OK: 4,
  W_OK: 2,
  X_OK: 1,
  UV_FS_COPYFILE_EXCL: 1,
  COPYFILE_EXCL: 1,
  UV_FS_COPYFILE_FICLONE: 2,
  COPYFILE_FICLONE: 2,
  UV_FS_COPYFILE_FICLONE_FORCE: 4,
  COPYFILE_FICLONE_FORCE: 4,
};
/** Stub for promises */
export const promises = {
  access: __stubFnDoNotCall,
  copyFile: __stubFnDoNotCall,
  cp: __stubFnDoNotCall,
  open: __stubFnDoNotCall,
  opendir: __stubFnDoNotCall,
  rename: __stubFnDoNotCall,
  truncate: __stubFnDoNotCall,
  rm: __stubFnDoNotCall,
  rmdir: __stubFnDoNotCall,
  mkdir: __stubFnDoNotCall,
  readdir: __stubFnDoNotCall,
  readlink: __stubFnDoNotCall,
  symlink: __stubFnDoNotCall,
  lstat: __stubFnDoNotCall,
  stat: __stubFnDoNotCall,
  link: __stubFnDoNotCall,
  unlink: __stubFnDoNotCall,
  chmod: __stubFnDoNotCall,
  lchmod: __stubFnDoNotCall,
  lchown: __stubFnDoNotCall,
  chown: __stubFnDoNotCall,
  utimes: __stubFnDoNotCall,
  lutimes: __stubFnDoNotCall,
  realpath: __stubFnDoNotCall,
  mkdtemp: __stubFnDoNotCall,
  writeFile: __stubFnDoNotCall,
  appendFile: __stubFnDoNotCall,
  readFile: __stubFnDoNotCall,
  watch: __stubFnDoNotCall,
};
